#ifndef AMIGALEXERCPP_H
#define AMIGALEXERCPP_H

#include <Qsci/qscilexercpp.h>

//
// C/C++ lexer extended with AmigaOS NDK 3.2R4 and MUI 5 (Stefan Stuntz)
// identifiers, extracted automatically from the user's own SDK headers:
//
//  - keyword set 2, "secondary keywords/identifiers" (style KeywordSet2):
//    real library FUNCTION CALLS - AmigaOS NDK 3.2R4 (clib/*_protos.h,
//    79 libraries/devices) plus MUI 5 (clib/muimaster_protos.h) and the
//    MUI convenience macros set()/nnset().
//
//  - keyword set 4, "global classes/typedefs" (style GlobalClass):
//    AmigaOS NDK 3.2R4 data TYPES from exec/types.h, plus MUI 5's
//    MUIA_/MUIM_/MUIC_/MUIV_ attribute, method, class and value tag
//    constants (libraries/mui.h). These aren't C types in the strict
//    sense, but QsciLexerCPP only exposes two extra, independently
//    colourable keyword sets in total - and MUIA_/MUIM_/MUIC_/MUIV_
//    tags are by far the most common identifiers in real MUI code, so
//    this is the more useful place for them than leaving them unstyled.
//
// QsciLexerCPP has no runtime "setKeywords()" - keyword sets are supplied
// by overriding the virtual keywords() method, which is exactly what this
// small subclass does, leaving all other sets to the base class.
//
class AmigaLexerCPP : public QsciLexerCPP
{
public:
    explicit AmigaLexerCPP(QObject *parent = nullptr) : QsciLexerCPP(parent) {}

    const char *keywords(int set) const override
    {
        if (set == 4)
            return amigaTypes();

        if (set == 2)
            return amigaFunctions();

        return QsciLexerCPP::keywords(set);
    }

private:
    // AmigaOS NDK 3.2R4 exec/types.h data types, plus MUI 5's
    // MUIA_/MUIM_/MUIC_/MUIV_ tag constants (1261, from libraries/mui.h)
    static const char *amigaTypes()
    {
        return
    "APTR BOOL BYTE BYTEBITS CONST_APTR CONST_STRPTR COUNT CPTR "
    "DOUBLE FLOAT LONG LONGBITS MUIA_Aboutmui_Application MUIA_AppMessage MUIA_ApplicationObject MUIA_Application_Active "
    "MUIA_Application_Author MUIA_Application_Base MUIA_Application_Broker MUIA_Application_BrokerHook MUIA_Application_BrokerPort MUIA_Application_BrokerPri MUIA_Application_Commands MUIA_Application_Copyright "
    "MUIA_Application_Description MUIA_Application_DiskObject MUIA_Application_DoubleStart MUIA_Application_DropObject MUIA_Application_ForceQuit MUIA_Application_HelpFile MUIA_Application_Iconified MUIA_Application_IconifyTitle "
    "MUIA_Application_Menu MUIA_Application_MenuAction MUIA_Application_MenuHelp MUIA_Application_Menustrip MUIA_Application_RexxHook MUIA_Application_RexxMsg MUIA_Application_RexxString MUIA_Application_SingleTask "
    "MUIA_Application_Sleep MUIA_Application_Title MUIA_Application_UseCommodities MUIA_Application_UseRexx MUIA_Application_UseScreenNotify MUIA_Application_UsedClasses MUIA_Application_Version MUIA_Application_Window "
    "MUIA_Application_WindowList MUIA_Argstring_Contents MUIA_Argstring_Template MUIA_Background MUIA_Balance_Quiet MUIA_Bitmap_Alpha MUIA_Bitmap_Bitmap MUIA_Bitmap_Height "
    "MUIA_Bitmap_MappingTable MUIA_Bitmap_Precision MUIA_Bitmap_RemappedBitmap MUIA_Bitmap_SourceColors MUIA_Bitmap_Transparent MUIA_Bitmap_UseFriend MUIA_Bitmap_Width MUIA_Bodychunk_Body "
    "MUIA_Bodychunk_Compression MUIA_Bodychunk_Depth MUIA_Bodychunk_Masking MUIA_Boopsi_Class MUIA_Boopsi_ClassID MUIA_Boopsi_MaxHeight MUIA_Boopsi_MaxWidth MUIA_Boopsi_MinHeight "
    "MUIA_Boopsi_MinWidth MUIA_Boopsi_Object MUIA_Boopsi_Remember MUIA_Boopsi_Smart MUIA_Boopsi_TagDrawInfo MUIA_Boopsi_TagScreen MUIA_Boopsi_TagWindow MUIA_BottomEdge "
    "MUIA_Coloradjust_Blue MUIA_Coloradjust_Green MUIA_Coloradjust_ModeID MUIA_Coloradjust_RGB MUIA_Coloradjust_Red MUIA_Colorfield_Blue MUIA_Colorfield_Green MUIA_Colorfield_Pen "
    "MUIA_Colorfield_RGB MUIA_Colorfield_Red MUIA_ContextMenu MUIA_ContextMenuHook MUIA_ContextMenuTrigger MUIA_ControlChar MUIA_CycleChain MUIA_Cycle_Active "
    "MUIA_Cycle_Entries MUIA_Datamap_AutoLock MUIA_Datamap_CopyKeys MUIA_Datamap_Count MUIA_Datamap_Pool MUIA_Dataspace_Count MUIA_Dataspace_Pool MUIA_Dirlist_AcceptPattern "
    "MUIA_Dirlist_Directory MUIA_Dirlist_DrawersOnly MUIA_Dirlist_ExAllType MUIA_Dirlist_FilesOnly MUIA_Dirlist_FilterDrawers MUIA_Dirlist_FilterHook MUIA_Dirlist_MultiSelDirs MUIA_Dirlist_NumBytes "
    "MUIA_Dirlist_NumBytes64 MUIA_Dirlist_NumDrawers MUIA_Dirlist_NumFiles MUIA_Dirlist_Path MUIA_Dirlist_Pattern MUIA_Dirlist_RejectIcons MUIA_Dirlist_RejectPattern MUIA_Dirlist_SortDirs "
    "MUIA_Dirlist_SortHighLow MUIA_Dirlist_SortType MUIA_Dirlist_Status MUIA_Disabled MUIA_DoubleBuffer MUIA_DoubleClick MUIA_Draggable MUIA_Dropable "
    "MUIA_Dtpic_Alpha MUIA_Dtpic_DarkenSelState MUIA_Dtpic_Fade MUIA_Dtpic_LightenOnMouse MUIA_Dtpic_Name MUIA_ExportID MUIA_Family_Child MUIA_Family_ChildCount "
    "MUIA_Family_List MUIA_Filepanel_AcceptPattern MUIA_Filepanel_DoMultiSelect MUIA_Filepanel_DoPatterns MUIA_Filepanel_DoSaveMode MUIA_Filepanel_Drawer MUIA_Filepanel_DrawersOnly MUIA_Filepanel_File "
    "MUIA_Filepanel_FilterDrawers MUIA_Filepanel_FilterFunc MUIA_Filepanel_Pattern MUIA_Filepanel_RejectIcons MUIA_Filepanel_RejectPattern MUIA_FillArea MUIA_FixHeight MUIA_FixHeightTxt "
    "MUIA_FixWidth MUIA_FixWidthTxt MUIA_Floating MUIA_Floattext_Justify MUIA_Floattext_KeepStyles MUIA_Floattext_SkipChars MUIA_Floattext_TabSize MUIA_Floattext_Text "
    "MUIA_Font MUIA_Fontpanel_ShowCollection MUIA_Frame MUIA_FrameDynamic MUIA_FramePhantomHoriz MUIA_FrameTitle MUIA_FrameVisible MUIA_Gadget_Gadget "
    "MUIA_Gauge_Current MUIA_Gauge_Divide MUIA_Gauge_Horiz MUIA_Gauge_InfoRate MUIA_Gauge_InfoText MUIA_Gauge_Max MUIA_Group_ActivePage MUIA_Group_Child "
    "MUIA_Group_ChildCount MUIA_Group_ChildList MUIA_Group_Columns MUIA_Group_Forward MUIA_Group_ForwardDepth MUIA_Group_Horiz MUIA_Group_HorizCenter MUIA_Group_HorizSpacing "
    "MUIA_Group_LayoutHook MUIA_Group_PageMode MUIA_Group_Rows MUIA_Group_SameHeight MUIA_Group_SameSize MUIA_Group_SameWidth MUIA_Group_Spacing MUIA_Group_VertCenter "
    "MUIA_Group_VertSpacing MUIA_Height MUIA_HelpLine MUIA_HelpNode MUIA_HorizDisappear MUIA_HorizWeight MUIA_Image_BuiltinSpec MUIA_Image_CopySpec "
    "MUIA_Image_FontMatch MUIA_Image_FontMatchHeight MUIA_Image_FontMatchString MUIA_Image_FontMatchWidth MUIA_Image_FreeHoriz MUIA_Image_FreeVert MUIA_Image_OldImage MUIA_Image_Spec "
    "MUIA_Image_State MUIA_InnerBottom MUIA_InnerLeft MUIA_InnerRight MUIA_InnerTop MUIA_InputMode MUIA_Keyadjust_AllowDoubleClick MUIA_Keyadjust_AllowMouseEvents "
    "MUIA_Keyadjust_AllowMultipleKeys MUIA_Keyadjust_AllowTripleClick MUIA_Keyadjust_Key MUIA_KnowsDisabled MUIA_LeftEdge MUIA_Levelmeter_Label MUIA_List_Active MUIA_List_AdjustHeight "
    "MUIA_List_AdjustWidth MUIA_List_AgainClick MUIA_List_AutoLineHeight MUIA_List_AutoVisible MUIA_List_ClickColumn MUIA_List_ColumnOrder MUIA_List_CompareHook MUIA_List_ConstructHook "
    "MUIA_List_DefClickColumn MUIA_List_DestructHook MUIA_List_DisplayHook MUIA_List_DoubleClick MUIA_List_DragSortable MUIA_List_DragType MUIA_List_DropMark MUIA_List_Editable "
    "MUIA_List_Entries MUIA_List_First MUIA_List_Format MUIA_List_HScrollerVisibility MUIA_List_HideColumn MUIA_List_Input MUIA_List_InsertPosition MUIA_List_LineHeight "
    "MUIA_List_MaxColumns MUIA_List_MinLineHeight MUIA_List_MultiSelect MUIA_List_MultiTestHook MUIA_List_Pool MUIA_List_PoolPuddleSize MUIA_List_PoolThreshSize MUIA_List_Quiet "
    "MUIA_List_ScrollerPos MUIA_List_SelectChange MUIA_List_ShowColumn MUIA_List_ShowDropMarks MUIA_List_SortColumn MUIA_List_SourceArray MUIA_List_Stripes MUIA_List_Title "
    "MUIA_List_TitleArray MUIA_List_TitleClick MUIA_List_TopPixel MUIA_List_TotalPixel MUIA_List_Visible MUIA_List_VisiblePixel MUIA_Listview_AgainClick MUIA_Listview_ClickColumn "
    "MUIA_Listview_DefClickColumn MUIA_Listview_DoubleClick MUIA_Listview_DragType MUIA_Listview_Input MUIA_Listview_List MUIA_Listview_MultiSelect MUIA_Listview_ScrollerPos MUIA_Listview_SelectChange "
    "MUIA_MaxHeight MUIA_MaxWidth MUIA_Menu_CopyStrings MUIA_Menu_Enabled MUIA_Menu_Title MUIA_Menuitem_AISSName MUIA_Menuitem_Checked MUIA_Menuitem_Checkit "
    "MUIA_Menuitem_CommandString MUIA_Menuitem_CopyStrings MUIA_Menuitem_Enabled MUIA_Menuitem_Exclude MUIA_Menuitem_FreeImage MUIA_Menuitem_Image MUIA_Menuitem_Menuitem MUIA_Menuitem_Shortcut "
    "MUIA_Menuitem_Title MUIA_Menuitem_Toggle MUIA_Menuitem_Trigger MUIA_Menustrip_CaseSensitive MUIA_Menustrip_Enabled MUIA_MinHeight MUIA_MinWidth MUIA_NoNotify "
    "MUIA_NoNotifyMethod MUIA_Numeric_CheckAllSizes MUIA_Numeric_Default MUIA_Numeric_Format MUIA_Numeric_Max MUIA_Numeric_Min MUIA_Numeric_RevLeftRight MUIA_Numeric_RevUpDown "
    "MUIA_Numeric_Reverse MUIA_Numeric_Value MUIA_ObjectID MUIA_Objectmap_AutoLock MUIA_Objectmap_CopyKeys MUIA_Objectmap_Count MUIA_Objectmap_Pool MUIA_Palette_Entries "
    "MUIA_Palette_Groupable MUIA_Palette_Names MUIA_Parent MUIA_Penadjust_PSIMode MUIA_Pendisplay_Pen MUIA_Pendisplay_RGBcolor MUIA_Pendisplay_Reference MUIA_Pendisplay_Spec "
    "MUIA_Pixmap_Alpha MUIA_Pixmap_CLUT MUIA_Pixmap_CLUTSize MUIA_Pixmap_CompressedSize MUIA_Pixmap_Compression MUIA_Pixmap_Data MUIA_Pixmap_Format MUIA_Pixmap_Height "
    "MUIA_Pixmap_TransparencyThreshold MUIA_Pixmap_UncompressedData MUIA_Pixmap_Width MUIA_PointerType MUIA_Popasl_Active MUIA_Popasl_StartHook MUIA_Popasl_StopHook MUIA_Popasl_Type "
    "MUIA_Poplist_Array MUIA_Popobject_Follow MUIA_Popobject_Light MUIA_Popobject_ObjStrHook MUIA_Popobject_Object MUIA_Popobject_StrObjHook MUIA_Popobject_Volatile MUIA_Popobject_WindowHook "
    "MUIA_Popstring_Button MUIA_Popstring_CloseHook MUIA_Popstring_OpenHook MUIA_Popstring_String MUIA_Popstring_Toggle MUIA_Pressed MUIA_Process_AutoLaunch MUIA_Process_Name "
    "MUIA_Process_Priority MUIA_Process_SourceClass MUIA_Process_SourceObject MUIA_Process_StackSize MUIA_Process_Task MUIA_Prop_DeltaFactor MUIA_Prop_Entries MUIA_Prop_First "
    "MUIA_Prop_Horiz MUIA_Prop_Slider MUIA_Prop_UseWinBorder MUIA_Prop_Visible MUIA_Pubscreenlist_Selection MUIA_Radio_Active MUIA_Radio_Entries MUIA_Rectangle_BarTitle "
    "MUIA_Rectangle_HBar MUIA_Rectangle_VBar MUIA_Register_Frame MUIA_Register_Titles MUIA_Revision MUIA_RightEdge MUIA_Scale_Horiz MUIA_Scrollbar_IncDecSize "
    "MUIA_Scrollbar_Type MUIA_Scrollgroup_AutoBars MUIA_Scrollgroup_Contents MUIA_Scrollgroup_FreeHoriz MUIA_Scrollgroup_FreeVert MUIA_Scrollgroup_HorizBar MUIA_Scrollgroup_NoHorizBar MUIA_Scrollgroup_NoVertBar "
    "MUIA_Scrollgroup_UseWinBorder MUIA_Scrollgroup_VertBar MUIA_Selected MUIA_Selectgroup_Active MUIA_ShortHelp MUIA_ShowMe MUIA_ShowSelState MUIA_Slave_Application "
    "MUIA_Slave_Class MUIA_Slave_Object MUIA_Slider_Horiz MUIA_Slider_Level MUIA_Slider_Max MUIA_Slider_Min MUIA_Slider_Quiet MUIA_Slider_Reverse "
    "MUIA_String_Accept MUIA_String_Acknowledge MUIA_String_AdvanceOnCR MUIA_String_AttachedList MUIA_String_BufferPos MUIA_String_Contents MUIA_String_DisplayPos MUIA_String_EditHook "
    "MUIA_String_Format MUIA_String_InactiveContents MUIA_String_Integer MUIA_String_Integer64 MUIA_String_LonelyEditHook MUIA_String_MaxLen MUIA_String_Placeholder MUIA_String_Reject "
    "MUIA_String_Secret MUIA_TextColor MUIA_Text_Contents MUIA_Text_ControlChar MUIA_Text_Copy MUIA_Text_Data MUIA_Text_HiChar MUIA_Text_Marking "
    "MUIA_Text_PreParse MUIA_Text_SetMax MUIA_Text_SetMin MUIA_Text_SetVMax MUIA_Text_Shorten MUIA_Text_Shortened MUIA_Textdata_Contents MUIA_Textdata_Encoding "
    "MUIA_Textdata_SourceBytes MUIA_Textdata_SourceEncoding MUIA_Textinput_AcceptChars MUIA_Textinput_Acknowledge MUIA_Textinput_AdvanceOnCR MUIA_Textinput_AttachedList MUIA_Textinput_AutoExpand MUIA_Textinput_Blinkrate "
    "MUIA_Textinput_Bookmark1 MUIA_Textinput_Bookmark2 MUIA_Textinput_Bookmark3 MUIA_Textinput_Changed MUIA_Textinput_Contents MUIA_Textinput_CursorPos MUIA_Textinput_CursorSize MUIA_Textinput_Cursorstyle "
    "MUIA_Textinput_DefaultPopup MUIA_Textinput_Editable MUIA_Textinput_Font MUIA_Textinput_Format MUIA_Textinput_HandleURLHook MUIA_Textinput_Integer MUIA_Textinput_IsNumeric MUIA_Textinput_IsOld "
    "MUIA_Textinput_Lines MUIA_Textinput_MarkEnd MUIA_Textinput_MarkStart MUIA_Textinput_MaxLen MUIA_Textinput_MaxLines MUIA_Textinput_MaxVal MUIA_Textinput_MinVal MUIA_Textinput_MinVersion "
    "MUIA_Textinput_MinimumWidth MUIA_Textinput_Multiline MUIA_Textinput_NoCopy MUIA_Textinput_NoExtraSpacing MUIA_Textinput_NoInput MUIA_Textinput_PreParse MUIA_Textinput_ProhibitParse MUIA_Textinput_Quiet "
    "MUIA_Textinput_RejectChars MUIA_Textinput_RemainActive MUIA_Textinput_ResetMarkOnCursor MUIA_Textinput_Secret MUIA_Textinput_SetMax MUIA_Textinput_SetMin MUIA_Textinput_SetVMax MUIA_Textinput_SetVMin "
    "MUIA_Textinput_Styles MUIA_Textinput_SuggestParse MUIA_Textinput_TabLen MUIA_Textinput_Tabs MUIA_Textinput_TmpExtension MUIA_Textinput_TopLine MUIA_Textinput_WordWrap MUIA_Textinputscroll_HorizBar "
    "MUIA_Textinputscroll_UseWinBorder MUIA_Textinputscroll_VertBar MUIA_Textinputscroll_VertScrollerOnly MUIA_Timer MUIA_Title_Clickable MUIA_Title_Closable MUIA_Title_EventHandlerPriority MUIA_Title_Newable "
    "MUIA_Title_OnLastClose MUIA_Title_Position MUIA_Title_Sortable MUIA_TopEdge MUIA_UserData MUIA_Version MUIA_VertDisappear MUIA_VertWeight "
    "MUIA_Virtgroup_Height MUIA_Virtgroup_Input MUIA_Virtgroup_Left MUIA_Virtgroup_Top MUIA_Virtgroup_TryFit MUIA_Virtgroup_Width MUIA_Volumelist_ExampleMode MUIA_Weight "
    "MUIA_Width MUIA_Window MUIA_WindowObject MUIA_Window_Activate MUIA_Window_ActiveObject MUIA_Window_AltHeight MUIA_Window_AltLeftEdge MUIA_Window_AltTopEdge "
    "MUIA_Window_AltWidth MUIA_Window_AppWindow MUIA_Window_Backdrop MUIA_Window_Borderless MUIA_Window_CloseGadget MUIA_Window_CloseRequest MUIA_Window_DefaultObject MUIA_Window_DepthGadget "
    "MUIA_Window_DisableKeys MUIA_Window_DragBar MUIA_Window_DrawInfo MUIA_Window_FancyDrawing MUIA_Window_Height MUIA_Window_ID MUIA_Window_InputEvent MUIA_Window_IsSubWindow "
    "MUIA_Window_LeftEdge MUIA_Window_Menu MUIA_Window_MenuAction MUIA_Window_Menustrip MUIA_Window_MouseObject MUIA_Window_NeedsMouseObject MUIA_Window_NoMenus MUIA_Window_Opacity "
    "MUIA_Window_Open MUIA_Window_PublicScreen MUIA_Window_RefWindow MUIA_Window_RootObject MUIA_Window_Screen MUIA_Window_ScreenTitle MUIA_Window_SizeGadget MUIA_Window_SizeRight "
    "MUIA_Window_Sleep MUIA_Window_Title MUIA_Window_TopEdge MUIA_Window_UseBottomBorderScroller MUIA_Window_UseLeftBorderScroller MUIA_Window_UseRightBorderScroller MUIA_Window_Width MUIA_Window_Window "
    "MUIC_Aboutmui MUIC_Aboutpage MUIC_Application MUIC_Applist MUIC_Area MUIC_Argstring MUIC_Audiocontrols MUIC_Audiomixer "
    "MUIC_Backgroundadjust MUIC_Balance MUIC_Bitmap MUIC_Bodychunk MUIC_Boopsi MUIC_Cclist MUIC_Coloradjust MUIC_Colorfield "
    "MUIC_Colorring MUIC_Configdata MUIC_Cycle MUIC_Datamap MUIC_Dataspace MUIC_Dirlist MUIC_Dtpic MUIC_Family "
    "MUIC_Filepanel MUIC_Floattext MUIC_Fontdisplay MUIC_Fontpanel MUIC_Frameadjust MUIC_Framedisplay MUIC_Frimagedisplay MUIC_Gadget "
    "MUIC_Gauge MUIC_Group MUIC_Image MUIC_Imageadjust MUIC_Imagebrowser MUIC_Imagedisplay MUIC_Imagespace MUIC_Keyadjust "
    "MUIC_Knob MUIC_Levelmeter MUIC_List MUIC_Listview MUIC_Mccprefs MUIC_Menu MUIC_Menubar MUIC_Menudisplay "
    "MUIC_Menuitem MUIC_Menustrip MUIC_Notify MUIC_Numeric MUIC_Numericbutton MUIC_Objectmap MUIC_Palette MUIC_Panel "
    "MUIC_Penadjust MUIC_Pendisplay MUIC_Pixmap MUIC_Popasl MUIC_Popframe MUIC_Popfrimage MUIC_Popimage MUIC_Poplist "
    "MUIC_Popmenu MUIC_Popobject MUIC_Poppen MUIC_Popscreen MUIC_Popstring MUIC_Process MUIC_Prop MUIC_Pubscreen "
    "MUIC_Pubscreenadjust MUIC_Pubscreenlist MUIC_Pubscreenpanel MUIC_Radio MUIC_Rectangle MUIC_Register MUIC_Rootgrp MUIC_Scale "
    "MUIC_Screenmodepanel MUIC_Screenspace MUIC_Scrmodelist MUIC_Scrollbar MUIC_Scrollgroup MUIC_Selectgroup MUIC_Semaphore MUIC_Settings "
    "MUIC_Settingsgroup MUIC_Slave MUIC_Slider MUIC_String MUIC_Text MUIC_Textdata MUIC_Textinput MUIC_Textinputscroll "
    "MUIC_Title MUIC_Virtgroup MUIC_Volumelist MUIC_Winborder MUIC_Window MUIM_Application_AboutMUI MUIM_Application_AddInputHandler MUIM_Application_BuildSettingsPanel "
    "MUIM_Application_CheckRefresh MUIM_Application_DefaultConfigItem MUIM_Application_Execute MUIM_Application_GetMenuCheck MUIM_Application_GetMenuState MUIM_Application_Input MUIM_Application_InputBuffered MUIM_Application_Load "
    "MUIM_Application_NewInput MUIM_Application_OpenConfigWindow MUIM_Application_PushMethod MUIM_Application_RemInputHandler MUIM_Application_ReturnID MUIM_Application_Run MUIM_Application_Save MUIM_Application_SetConfigItem "
    "MUIM_Application_SetMenuCheck MUIM_Application_SetMenuState MUIM_Application_ShowHelp MUIM_Application_UnpushMethod MUIM_AskMinMax MUIM_BoopsiQuery MUIM_CallHook MUIM_Cleanup "
    "MUIM_ContextMenuAdd MUIM_ContextMenuBuild MUIM_ContextMenuChoice MUIM_CreateBubble MUIM_CreateDragImage MUIM_CreateShortHelp MUIM_Datamap_Clear MUIM_Datamap_Find "
    "MUIM_Datamap_Get MUIM_Datamap_Iterate MUIM_Datamap_IterationKey MUIM_Datamap_Remove MUIM_Datamap_Set MUIM_Dataspace_Add MUIM_Dataspace_Clear MUIM_Dataspace_Find "
    "MUIM_Dataspace_Get MUIM_Dataspace_Merge MUIM_Dataspace_ReadIFF MUIM_Dataspace_Remove MUIM_Dataspace_WriteIFF MUIM_DeleteBubble MUIM_DeleteDragImage MUIM_DeleteShortHelp "
    "MUIM_Dirlist_ReRead MUIM_Dirlist_Rename MUIM_Dirlist_SetComment MUIM_Dirlist_SetProtection MUIM_DoDrag MUIM_DragBegin MUIM_DragDrop MUIM_DragEvent "
    "MUIM_DragFinish MUIM_DragQuery MUIM_DragReport MUIM_Draw MUIM_DrawBackground MUIM_DrawBackgroundParent MUIM_Export MUIM_Family_AddHead "
    "MUIM_Family_AddTail MUIM_Family_DoChildMethods MUIM_Family_GetChild MUIM_Family_Insert MUIM_Family_Remove MUIM_Family_Reorder MUIM_Family_Sort MUIM_Family_Transfer "
    "MUIM_FindObject MUIM_FindUData MUIM_Floattext_Append MUIM_GetConfigItem MUIM_GetUData MUIM_GoActive MUIM_GoInactive MUIM_Group_AddHead "
    "MUIM_Group_AddTail MUIM_Group_ExitChange MUIM_Group_ExitChange2 MUIM_Group_InitChange MUIM_Group_MoveMember MUIM_Group_Remove MUIM_Group_Reorder MUIM_Group_Sort "
    "MUIM_HandleEvent MUIM_HandleInput MUIM_Hide MUIM_Import MUIM_KillNotify MUIM_KillNotifyObj MUIM_Layout MUIM_List_Clear "
    "MUIM_List_Compare MUIM_List_Construct MUIM_List_CreateEditObject MUIM_List_CreateImage MUIM_List_DeleteImage MUIM_List_Destruct MUIM_List_Display MUIM_List_Edit "
    "MUIM_List_EditDone MUIM_List_EndEdit MUIM_List_Exchange MUIM_List_GetEntry MUIM_List_Insert MUIM_List_InsertSingle MUIM_List_Jump MUIM_List_Move "
    "MUIM_List_NextSelected MUIM_List_QueryColumnWidth MUIM_List_Redraw MUIM_List_Remove MUIM_List_Select MUIM_List_Sort MUIM_List_SortEntries MUIM_List_TestPos "
    "MUIM_Mccprefs_ConfigToGadgets MUIM_Mccprefs_GadgetsToConfig MUIM_Mccprefs_RegisterGadget MUIM_Menustrip_ExitChange MUIM_Menustrip_InitChange MUIM_Menustrip_Popup MUIM_Menustrip_WillOpen MUIM_MultiSet "
    "MUIM_NoNotifySet MUIM_Notify MUIM_Numeric_Decrease MUIM_Numeric_Increase MUIM_Numeric_ScaleToValue MUIM_Numeric_SetDefault MUIM_Numeric_Stringify MUIM_Numeric_ValueToScale "
    "MUIM_Objectmap_Clear MUIM_Objectmap_Find MUIM_Objectmap_Iterate MUIM_Objectmap_IterationKey MUIM_Objectmap_Remove MUIM_Objectmap_Set MUIM_Panel_Run MUIM_Pendisplay_SetColormap "
    "MUIM_Pendisplay_SetMUIPen MUIM_Pendisplay_SetRGB MUIM_Pixmap_DrawSection MUIM_Popstring_Close MUIM_Popstring_Open MUIM_Process_Kill MUIM_Process_Launch MUIM_Process_Process "
    "MUIM_Process_Signal MUIM_Prop_Decrease MUIM_Prop_Increase MUIM_Relayout MUIM_Semaphore_Attempt MUIM_Semaphore_AttemptShared MUIM_Semaphore_Obtain MUIM_Semaphore_ObtainShared "
    "MUIM_Semaphore_Release MUIM_Set MUIM_SetAsString MUIM_SetUData MUIM_SetUDataOnce MUIM_Settingsgroup_ConfigToGadgets MUIM_Settingsgroup_GadgetsToConfig MUIM_Setup "
    "MUIM_Show MUIM_Slave_Cleanup MUIM_Slave_Dispatch MUIM_Slave_Error MUIM_Slave_Setup MUIM_Slave_SignalsReceived MUIM_Text MUIM_TextDim "
    "MUIM_Textdata_Convert MUIM_Textinput_Acknowledge MUIM_Textinput_AppendText MUIM_Textinput_DoBS MUIM_Textinput_DoBSSOL MUIM_Textinput_DoBSWord MUIM_Textinput_DoBottom MUIM_Textinput_DoCopy "
    "MUIM_Textinput_DoCopyCut MUIM_Textinput_DoCut MUIM_Textinput_DoCutLine MUIM_Textinput_DoDecrementDec MUIM_Textinput_DoDel MUIM_Textinput_DoDelEOL MUIM_Textinput_DoDelLine MUIM_Textinput_DoDelWord "
    "MUIM_Textinput_DoDown MUIM_Textinput_DoGotoBookmark1 MUIM_Textinput_DoGotoBookmark2 MUIM_Textinput_DoGotoBookmark3 MUIM_Textinput_DoIncrementDec MUIM_Textinput_DoInsertFile MUIM_Textinput_DoLeft MUIM_Textinput_DoLineEnd "
    "MUIM_Textinput_DoLineStart MUIM_Textinput_DoMarkAll MUIM_Textinput_DoMarkStart MUIM_Textinput_DoNextGadget MUIM_Textinput_DoNextWord MUIM_Textinput_DoPageDown MUIM_Textinput_DoPageUp MUIM_Textinput_DoPaste "
    "MUIM_Textinput_DoPopup MUIM_Textinput_DoPrevWord MUIM_Textinput_DoRedo MUIM_Textinput_DoRevert MUIM_Textinput_DoRight MUIM_Textinput_DoSetBookmark1 MUIM_Textinput_DoSetBookmark2 MUIM_Textinput_DoSetBookmark3 "
    "MUIM_Textinput_DoTab MUIM_Textinput_DoToggleCase MUIM_Textinput_DoToggleCaseEOW MUIM_Textinput_DoToggleWordwrap MUIM_Textinput_DoTop MUIM_Textinput_DoUndo MUIM_Textinput_DoUp MUIM_Textinput_DoubleClick "
    "MUIM_Textinput_ExternalEdit MUIM_Textinput_HandleChar MUIM_Textinput_HandleURL MUIM_Textinput_InsertFromFile MUIM_Textinput_InsertText MUIM_Textinput_LoadFromFile MUIM_Textinput_SaveToFile MUIM_Textinput_TranslateEvent "
    "MUIM_Title_Close MUIM_Title_FindPage MUIM_Title_New MUIM_UpdateConfig MUIM_WhichPointerType MUIM_Window_AddEventHandler MUIM_Window_Cleanup MUIM_Window_GetMenuCheck "
    "MUIM_Window_GetMenuState MUIM_Window_RemEventHandler MUIM_Window_ScreenToBack MUIM_Window_ScreenToFront MUIM_Window_SetCycleChain MUIM_Window_SetMenuCheck MUIM_Window_SetMenuState MUIM_Window_Setup "
    "MUIM_Window_Snapshot MUIM_Window_ToBack MUIM_Window_ToFront MUIM_WriteLong MUIM_WriteString MUIV_Application_Load_ENV MUIV_Application_Load_ENVARC MUIV_Application_OCW_ScreenPage "
    "MUIV_Application_ReturnID_Quit MUIV_Application_Save_ENV MUIV_Application_Save_ENVARC MUIV_ContextMenuBuild_Default MUIV_CreateBubble_DontHidePointer MUIV_Cycle_Active_Next MUIV_Cycle_Active_Prev MUIV_Dirlist_Rename_Active "
    "MUIV_Dirlist_SetComment_Active MUIV_Dirlist_SetProtection_Active MUIV_Dirlist_SortDirs_First MUIV_Dirlist_SortDirs_Last MUIV_Dirlist_SortDirs_Mix MUIV_Dirlist_SortType_Comment MUIV_Dirlist_SortType_Count MUIV_Dirlist_SortType_Date "
    "MUIV_Dirlist_SortType_DateTime MUIV_Dirlist_SortType_Flags MUIV_Dirlist_SortType_Name MUIV_Dirlist_SortType_Size MUIV_Dirlist_SortType_Time MUIV_Dirlist_SortType_Type MUIV_Dirlist_SortType_Used MUIV_Dirlist_Status_Invalid "
    "MUIV_Dirlist_Status_Reading MUIV_Dirlist_Status_Valid MUIV_DragQuery_Accept MUIV_DragQuery_Refuse MUIV_DragReport_Abort MUIV_DragReport_Continue MUIV_DragReport_Lock MUIV_DragReport_Refresh "
    "MUIV_EveryTime MUIV_Family_GetChild_First MUIV_Family_GetChild_Iterate MUIV_Family_GetChild_Last MUIV_Family_GetChild_Next MUIV_Family_GetChild_Previous MUIV_Font_Big MUIV_Font_Bubble "
    "MUIV_Font_Button MUIV_Font_Count MUIV_Font_Fixed MUIV_Font_Gauge MUIV_Font_Huge MUIV_Font_Inherit MUIV_Font_Last MUIV_Font_List "
    "MUIV_Font_Menu MUIV_Font_Normal MUIV_Font_Slider MUIV_Font_Tab MUIV_Font_Tiny MUIV_Font_Title MUIV_Fontpanel_ShowCollection_All MUIV_Fontpanel_ShowCollection_Bitmap "
    "MUIV_Fontpanel_ShowCollection_FixedWidth MUIV_Fontpanel_ShowCollection_TrueType MUIV_Fontpanel_ShowCollection_User MUIV_Frame_Button MUIV_Frame_Count MUIV_Frame_Gauge MUIV_Frame_GaugeInner MUIV_Frame_Group "
    "MUIV_Frame_GroupTitle MUIV_Frame_ImageButton MUIV_Frame_InputList MUIV_Frame_Menudisplay MUIV_Frame_MenudisplayMenu MUIV_Frame_None MUIV_Frame_Page MUIV_Frame_PopUp "
    "MUIV_Frame_Prop MUIV_Frame_PropKnob MUIV_Frame_ReadList MUIV_Frame_Register MUIV_Frame_RegisterTitle MUIV_Frame_Requester MUIV_Frame_Slider MUIV_Frame_SliderKnob "
    "MUIV_Frame_String MUIV_Frame_Text MUIV_Frame_Virtual MUIV_Frame_Window MUIV_Group_ActivePage_Advance MUIV_Group_ActivePage_First MUIV_Group_ActivePage_Last MUIV_Group_ActivePage_Next "
    "MUIV_Group_ActivePage_Prev MUIV_Group_GetChild_First MUIV_Group_GetChild_Iterate MUIV_Group_GetChild_Last MUIV_Group_GetChild_Next MUIV_Group_GetChild_Previous MUIV_Group_HorizCenter_Center MUIV_Group_HorizCenter_Left "
    "MUIV_Group_HorizCenter_Right MUIV_Group_Spacing_Default MUIV_Group_Spacing_Percent MUIV_Group_VertCenter_Bottom MUIV_Group_VertCenter_Center MUIV_Group_VertCenter_Top MUIV_InputMode_Immediate MUIV_InputMode_None "
    "MUIV_InputMode_RelVerify MUIV_InputMode_Toggle MUIV_List_Active_Bottom MUIV_List_Active_Down MUIV_List_Active_Off MUIV_List_Active_PageDown MUIV_List_Active_PageUp MUIV_List_Active_Top "
    "MUIV_List_Active_Up MUIV_List_CompareHook_String MUIV_List_CompareHook_StringArray MUIV_List_ConstructHook_String MUIV_List_ConstructHook_StringArray MUIV_List_DestructHook_String MUIV_List_DestructHook_StringArray MUIV_List_DisplayHook_String "
    "MUIV_List_DisplayHook_StringArray MUIV_List_DragType_Immediate MUIV_List_DragType_None MUIV_List_EditEntry_Active MUIV_List_Edit_Active MUIV_List_EndEdit_Abort MUIV_List_EndEdit_Done MUIV_List_EndEdit_Down "
    "MUIV_List_EndEdit_Next MUIV_List_EndEdit_Prev MUIV_List_EndEdit_Up MUIV_List_Exchange_Active MUIV_List_Exchange_Bottom MUIV_List_Exchange_Next MUIV_List_Exchange_Previous MUIV_List_Exchange_Top "
    "MUIV_List_GetEntry_Active MUIV_List_HScrollerVisibility_Always MUIV_List_HScrollerVisibility_Auto MUIV_List_HScrollerVisibility_Never MUIV_List_Insert_Active MUIV_List_Insert_Bottom MUIV_List_Insert_Sorted MUIV_List_Insert_Top "
    "MUIV_List_Jump_Active MUIV_List_Jump_Bottom MUIV_List_Jump_Down MUIV_List_Jump_Top MUIV_List_Jump_Up MUIV_List_Move_Active MUIV_List_Move_Bottom MUIV_List_Move_Next "
    "MUIV_List_Move_Previous MUIV_List_Move_Top MUIV_List_MultiSelect_Always MUIV_List_MultiSelect_Default MUIV_List_MultiSelect_None MUIV_List_MultiSelect_Shifted MUIV_List_NextSelected_End MUIV_List_NextSelected_Start "
    "MUIV_List_Redraw_Active MUIV_List_Redraw_All MUIV_List_Redraw_Entry MUIV_List_Remove_Active MUIV_List_Remove_First MUIV_List_Remove_Last MUIV_List_Remove_Selected MUIV_List_ScrollerPos_Default "
    "MUIV_List_ScrollerPos_Left MUIV_List_ScrollerPos_None MUIV_List_ScrollerPos_Right MUIV_List_Select_Active MUIV_List_Select_All MUIV_List_Select_Ask MUIV_List_Select_Off MUIV_List_Select_On "
    "MUIV_List_Select_Toggle MUIV_Listview_DragType_Immediate MUIV_Listview_DragType_None MUIV_Listview_MultiSelect_Always MUIV_Listview_MultiSelect_Default MUIV_Listview_MultiSelect_None MUIV_Listview_MultiSelect_Shifted MUIV_Listview_ScrollerPos_Default "
    "MUIV_Listview_ScrollerPos_Left MUIV_Listview_ScrollerPos_None MUIV_Listview_ScrollerPos_Right MUIV_Menuitem_Shortcut_Check MUIV_NotTriggerValue MUIV_Notify_Application MUIV_Notify_Parent MUIV_Notify_ParentParent "
    "MUIV_Notify_ParentParentParent MUIV_Notify_Self MUIV_Notify_Window MUIV_Palette_Entry_End MUIV_Pixmap_Compression_BZip2 MUIV_Pixmap_Compression_LZMA MUIV_Pixmap_Compression_None MUIV_Pixmap_Compression_RLE "
    "MUIV_Pixmap_Compression_Z MUIV_Pixmap_Format_ARGB32 MUIV_Pixmap_Format_CLUT8 MUIV_Pixmap_Format_RGB24 MUIV_PointerType_Alias MUIV_PointerType_Busy MUIV_PointerType_Cell MUIV_PointerType_ColumnResize "
    "MUIV_PointerType_ContextMenu MUIV_PointerType_Copy MUIV_PointerType_Count MUIV_PointerType_Cross MUIV_PointerType_DragAndDrop MUIV_PointerType_EastResize MUIV_PointerType_EastWestResize MUIV_PointerType_Hand "
    "MUIV_PointerType_Help MUIV_PointerType_Link MUIV_PointerType_Menu MUIV_PointerType_NoDrop MUIV_PointerType_None MUIV_PointerType_Normal MUIV_PointerType_NorthEastResize MUIV_PointerType_NorthEastSouthWestResize "
    "MUIV_PointerType_NorthResize MUIV_PointerType_NorthSouthResize MUIV_PointerType_NorthWestResize MUIV_PointerType_NorthWestSouthEastResize MUIV_PointerType_NotAllowed MUIV_PointerType_Parent MUIV_PointerType_Pen MUIV_PointerType_Progress "
    "MUIV_PointerType_Rotate MUIV_PointerType_Rotation MUIV_PointerType_RowResize MUIV_PointerType_Rubber MUIV_PointerType_ScrollAll MUIV_PointerType_Select MUIV_PointerType_Smudge MUIV_PointerType_SouthEastResize "
    "MUIV_PointerType_SouthResize MUIV_PointerType_SouthWestResize MUIV_PointerType_Text MUIV_PointerType_VerticalText MUIV_PointerType_WestResize MUIV_PointerType_ZoomIn MUIV_PointerType_ZoomOut MUIV_Prop_UseWinBorder_Bottom "
    "MUIV_Prop_UseWinBorder_Left MUIV_Prop_UseWinBorder_None MUIV_Prop_UseWinBorder_Right MUIV_PushMethod_Delay MUIV_Register_Titles_Frame MUIV_Register_Titles_UData MUIV_Requester_Image_Default MUIV_Requester_Image_Error "
    "MUIV_Requester_Image_Info MUIV_Requester_Image_InsertDisk MUIV_Requester_Image_None MUIV_Requester_Image_Question MUIV_Requester_Image_Warning MUIV_Scrollbar_Type_Bottom MUIV_Scrollbar_Type_Default MUIV_Scrollbar_Type_None "
    "MUIV_Scrollbar_Type_Sym MUIV_Scrollbar_Type_Top MUIV_Selectgroup_Active_Next MUIV_Selectgroup_Active_Prev MUIV_String_Format_Center MUIV_String_Format_Left MUIV_String_Format_Right MUIV_Text_Shorten_Cutoff "
    "MUIV_Text_Shorten_ElideCenter MUIV_Text_Shorten_ElideLeft MUIV_Text_Shorten_ElideRight MUIV_Text_Shorten_Hide MUIV_Text_Shorten_Nothing MUIV_Textinput_Font_Fixed MUIV_Textinput_Font_Normal MUIV_Textinput_Format_Center "
    "MUIV_Textinput_Format_Centre MUIV_Textinput_Format_Left MUIV_Textinput_Format_Right MUIV_Textinput_NoMark MUIV_Textinput_ParseB_Misspell MUIV_Textinput_ParseB_URL MUIV_Textinput_ParseF_Misspell MUIV_Textinput_ParseF_URL "
    "MUIV_Textinput_Styles_Email MUIV_Textinput_Styles_HTML MUIV_Textinput_Styles_IRC MUIV_Textinput_Styles_MUI MUIV_Textinput_Styles_None MUIV_Textinput_Tabs_Disk MUIV_Textinput_Tabs_Ignore MUIV_Textinput_Tabs_Spaces "
    "MUIV_Textinput_Tabs_Tabs MUIV_Title_EventHandlerPriority_Default MUIV_Title_OnLastClose_Remove MUIV_Title_OnLastClose_WindowAction MUIV_Title_Position_Bottom MUIV_Title_Position_Left MUIV_Title_Position_Right MUIV_Title_Position_Top "
    "MUIV_TriggerValue MUIV_Window_ActiveObject_Down MUIV_Window_ActiveObject_Left MUIV_Window_ActiveObject_Next MUIV_Window_ActiveObject_None MUIV_Window_ActiveObject_Prev MUIV_Window_ActiveObject_Right MUIV_Window_ActiveObject_Up "
    "MUIV_Window_AltHeight_MinMax MUIV_Window_AltHeight_Scaled MUIV_Window_AltHeight_Screen MUIV_Window_AltHeight_Visible MUIV_Window_AltLeftEdge_Centered MUIV_Window_AltLeftEdge_Moused MUIV_Window_AltLeftEdge_NoChange MUIV_Window_AltTopEdge_Centered "
    "MUIV_Window_AltTopEdge_Delta MUIV_Window_AltTopEdge_Moused MUIV_Window_AltTopEdge_NoChange MUIV_Window_AltWidth_MinMax MUIV_Window_AltWidth_Scaled MUIV_Window_AltWidth_Screen MUIV_Window_AltWidth_Visible MUIV_Window_Height_Default "
    "MUIV_Window_Height_MinMax MUIV_Window_Height_Scaled MUIV_Window_Height_Screen MUIV_Window_Height_Visible MUIV_Window_LeftEdge_Centered MUIV_Window_LeftEdge_Moused MUIV_Window_LeftEdge_Right MUIV_Window_Menu_NoMenu "
    "MUIV_Window_TopEdge_Bottom MUIV_Window_TopEdge_Centered MUIV_Window_TopEdge_Delta MUIV_Window_TopEdge_Moused MUIV_Window_Width_Default MUIV_Window_Width_MinMax MUIV_Window_Width_Scaled MUIV_Window_Width_Screen "
    "MUIV_Window_Width_Visible RPTR SHORT STRPTR TEXT UBYTE UCOUNT ULONG "
    "USHORT UWORD VOID WORD WORDBITS ";
    }

    // AmigaOS NDK 3.2R4 library function names (1413, from clib/*_protos.h
    // of the following 79 libraries/devices):
    // alib, alib_stdio, amigaguide, arexx, asl, battclock, battmem, bevel, bitmap, bullet
    // button, cardres, checkbox, chooser, cia, clicktab, colorwheel, commodities, console, datatypes
    // datebrowser, ddebug, debug, disk, diskfont, dos, drawlist, exec, expansion, fuelgauge
    // gadtools, getcolor, getfile, getfont, getscreenmode, glyph, graphics, icon, iffparse, input
    // integer, intuition, keymap, label, layers, layout, listbrowser, locale, lowlevel, mathffp
    // mathieeedoubbas, mathieeedoubtrans, mathieeesingbas, mathieeesingtrans, mathtrans, misc, nonvolatile, palette, penmap, potgo
    // radiobutton, ramdrive, reaction_lib, realtime, requester, rexxsyslib, scroller, sketchboard, slider, space
    // speedbar, string, texteditor, timer, trackfile, translator, utility, virtual, wb, window
    // ...plus MUI 5 (Stefan Stuntz) library functions and convenience
    // macros (36, from clib/muimaster_protos.h + set()/nnset())
    static const char *amigaFunctions()
    {
        return
    "ACrypt AREXX_GetClass AbleICR AbortAslRequest AbortIO AbortPkt ActivateAslRequest ActivateCxObj "
    "ActivateGadget ActivateLayoutGadget ActivateWindow AddAmigaGuideHost AddAmigaGuideHostA AddAnimOb AddAppIcon AddAppIconA "
    "AddAppMenuItem AddAppMenuItemA AddAppWindow AddAppWindowA AddAppWindowDropZone AddAppWindowDropZoneA AddBob AddBootNode "
    "AddBuffers AddClass AddConfigDev AddDTObject AddDevice AddDosEntry AddDosNode AddFont "
    "AddFreeList AddGList AddGadget AddHead AddHeadMinList AddICRVector AddIEvents AddIntServer "
    "AddKBInt AddLibrary AddMemHandler AddMemList AddNamedObject AddPart AddPort AddResource "
    "AddSegment AddSemaphore AddTOF AddTail AddTailMinList AddTask AddTime AddTimerInt "
    "AddVBlankInt AddVSprite Alert AllocAbs AllocAslRequest AllocAslRequestTags AllocBitMap AllocBoardMem "
    "AllocChooserNode AllocChooserNodeA AllocClickTabNode AllocClickTabNodeA AllocConfigDev AllocDBufInfo AllocDosObject AllocDosObjectTagList "
    "AllocDosObjectTags AllocEntry AllocExpansionMem AllocFileRequest AllocIFF AllocLBColumnInfo AllocLBColumnInfoA AllocListBrowserNode "
    "AllocListBrowserNodeA AllocLocalItem AllocMem AllocMiscResource AllocNamedObject AllocNamedObjectA AllocPooled AllocPotBits "
    "AllocRadioButtonNode AllocRadioButtonNodeA AllocRaster AllocRemember AllocScreenBuffer AllocSignal AllocSpeedButtonNode AllocSpeedButtonNodeA "
    "AllocSpriteData AllocSpriteDataA AllocTrap AllocUnit AllocVec Allocate AllocateTagItems AlohaWorkbench "
    "Amiga2Date AmigaGuideSignal AndRectRegion AndRegionRegion Animate ApplyTagChanges AreaDraw AreaEllipse "
    "AreaEnd AreaMove ArgArrayDone ArgArrayInit ArgInt ArgString AskFont AskKeyMapDefault "
    "AskSoftStyle AslRequest AslRequestTags AssignAdd AssignLate AssignLock AssignPath AttachCxObj "
    "AttachPalExtra AttemptLockDosList AttemptLockLayerRom AttemptRemNamedObject AttemptSemaphore AttemptSemaphoreShared AutoRequest AvailFonts "
    "AvailMem BEVEL_GetClass BITMAP_GetClass BUTTON_GetClass BeginCardAccess BeginIO BeginRefresh BeginUpdate "
    "BehindLayer BestModeID BestModeIDA BitMapScale BltBitMap BltBitMapRastPort BltClear BltMaskBitMapRastPort "
    "BltPattern BltTemplate BrowserNodes BrowserNodesA BuildEasyRequest BuildEasyRequestArgs BuildSysRequest BumpRevision "
    "BumpRevisionLength CBump CDInputHandler CHECKBOX_GetClass CHOOSER_GetClass CLICKTAB_GetClass CMove CWait "
    "CacheClearE CacheClearU CacheControl CachePostDMA CachePreDMA CalcIVG CallHook CallHookA "
    "CallHookPkt CardAccessSpeed CardChangeCount CardForceChange CardInterface CardMiscControl CardProgramVoltage CardResetCard "
    "CardResetRemove Cause ChangeExtSprite ChangeExtSpriteA ChangeMode ChangeScreenBuffer ChangeSprite ChangeToSelectedIconColor "
    "ChangeVPBitMap ChangeWindowBox ChangeWorkbenchSelection ChangeWorkbenchSelectionA CheckDate CheckIO CheckRexxMsg CheckSignal "
    "ChooserLabels ChooserLabelsA ClearCxObjError ClearDMRequest ClearEOL ClearMenuStrip ClearPointer ClearRectRegion "
    "ClearRegion ClearRexxMsg ClearScreen Cli CliInitNewcli CliInitRun ClickTabs ClickTabsA "
    "ClipBlit CloneTagItems Close CloseAmigaGuide CloseCatalog CloseClipboard CloseDevice CloseEngine "
    "CloseFont CloseIFF CloseLibrary CloseLocale CloseMonitor CloseOutlineFont CloseScreen CloseWindow "
    "CloseWorkBench CloseWorkbenchObject CloseWorkbenchObjectA CmpTime CoerceMethod CoerceMethodA CoerceMode ColdReboot "
    "CollectionChunk CollectionChunks CompareDates ConfigBoard ConfigChain ConvToLower ConvToUpper ConvertHSBToRGB "
    "ConvertRGBToHSB CopyDTMethods CopyDTTriggerMethods CopyMem CopyMemQuick CopySBitMap CopyTuple CreateArgstring "
    "CreateBehindHookLayer CreateBehindLayer CreateContext CreateCxObj CreateDir CreateExtIO CreateGadget CreateGadgetA "
    "CreateIORequest CreateMenus CreateMenusA CreateMsgPort CreateNewProc CreateNewProcTagList CreateNewProcTags CreatePlayer "
    "CreatePlayerA CreatePool CreatePort CreateProc CreateRexxHostPort CreateRexxMsg CreateStdIO CreateTask "
    "CreateUpfrontHookLayer CreateUpfrontLayer CurrentChunk CurrentDir CurrentTime CxBroker CxMsgData CxMsgID "
    "CxMsgType CxObjError CxObjType DATEBROWSER_GetClass DDoFmt DGetCh DGetChar DGetNum "
    "DMayGetCh DMayGetChar DPrintF DPutCh DPutChar DPutFmt DPutS DPutStr "
    "DRAWLIST_GetClass Date2Amiga DateStamp DateToStr Deallocate Debug Delay DeleteArgstring "
    "DeleteCxObj DeleteCxObjAll DeleteDiskObject DeleteExtIO DeleteFile DeleteIORequest DeleteLayer DeleteMsgPort "
    "DeleteNV DeletePlayer DeletePool DeletePort DeleteRexxHostPort DeleteRexxMsg DeleteStdIO DeleteTask "
    "DeleteVar DeviceProc DeviceTuple Disable DisownBlitter DisplayAlert DisplayBeep DisposeCxMsg "
    "DisposeDTObject DisposeFontContents DisposeLayerInfo DisposeObject DisposeRegion DivertCxMsg DoAsyncLayout DoCollision "
    "DoDTMethod DoDTMethodA DoGadgetMethod DoGadgetMethodA DoHookClipRects DoIO DoMethod DoMethodA "
    "DoPkt DoPkt0 DoPkt1 DoPkt2 DoPkt3 DoPkt4 DoShellMethod DoShellMethodTagList "
    "DoSuperMethod DoSuperMethodA DoTimer DoubleClick Draw DrawBevelBox DrawBevelBoxA DrawBorder "
    "DrawEllipse DrawGList DrawIconState DrawIconStateA DrawImage DrawImageState DupDiskObject DupDiskObjectA "
    "DupLock DupLockFromFH ECloseEngine EObtainInfo EObtainInfoA EOpenEngine EReleaseInfo EReleaseInfoA "
    "ESetInfo ESetInfoA EasyRequest EasyRequestArgs ElapsedTime Enable EndCardAccess EndNotify "
    "EndRefresh EndRequest EndUpdate Enqueue EnqueueCxObj EntryHandler EraseImage EraseRect "
    "ErrorOutput ErrorReport ExAll ExAllEnd ExNext Examine ExamineFH Execute "
    "Exit ExitHandler ExpungeXRef ExtendFont ExtendFontTags ExternalSync FGetC FGets "
    "FPrintf FPutC FPuts FRead FUELGAUGE_GetClass FWrite FWritef FastRand "
    "FattenLayerInfo Fault FilePart FillRexxMsg FilterTagChanges FilterTagItems FindArg FindCliProc "
    "FindCollection FindColor FindConductor FindConfigDev FindDisplayInfo FindDosEntry FindLocalItem FindMethod "
    "FindName FindNamedObject FindPort FindProp FindPropContext FindResident FindSegment FindSemaphore "
    "FindTagItem FindTask FindToolType FindTriggerMethod FindVar Flood Flush FlushLayoutDomainCache "
    "FontExtent Forbid Format FormatDate FormatString FreeAlloc FreeArgs FreeAslRequest "
    "FreeBitMap FreeBoardMem FreeBrowserNodes FreeChooserLabels FreeChooserNode FreeClass FreeClickTabNode FreeClickTabs "
    "FreeColorMap FreeConfigDev FreeCopList FreeCprList FreeDBufInfo FreeDTMethods FreeDeviceProc FreeDiskObject "
    "FreeDosEntry FreeDosObject FreeEntry FreeExpansionMem FreeFileRequest FreeFree FreeFreeList FreeGBuffers "
    "FreeGadgets FreeIEvents FreeIFF FreeLBColumnInfo FreeListBrowserList FreeListBrowserNode FreeLocalItem FreeMem "
    "FreeMenus FreeMiscResource FreeNVData FreeNamedObject FreePooled FreePotBits FreeRadioButtonNode FreeRadioButtons "
    "FreeRaster FreeRemember FreeRexxMsg FreeScreenBuffer FreeScreenDrawInfo FreeSignal FreeSpeedButtonNode FreeSprite "
    "FreeSpriteData FreeSysRequest FreeTagItems FreeTrap FreeUnit FreeVPortCopLists FreeVec FreeVisualInfo "
    "GETCOLOR_GetClass GETFILE_GetClass GETFONT_GetClass GETSCREENMODE_GetClass GLYPH_GetClass GT_BeginRefresh GT_EndRefresh GT_FilterIMsg "
    "GT_GetGadgetAttrs GT_GetGadgetAttrsA GT_GetIMsg GT_PostFilterIMsg GT_RefreshWindow GT_ReplyIMsg GT_SetGadgetAttrs GT_SetGadgetAttrsA "
    "GadgetMouse GetAPen GetAmigaGuideAttr GetAmigaGuideMsg GetAmigaGuideString GetArgStr GetAttr GetAttrs "
    "GetAttrsA GetBPen GetBitMapAttr GetCC GetCardMap GetCatalogStr GetChooserNodeAttrs GetChooserNodeAttrsA "
    "GetClickTabNodeAttrs GetClickTabNodeAttrsA GetCode GetColorMap GetConsoleTask GetCopyNV GetCurrentBinding GetCurrentDir "
    "GetCurrentDirName GetDTAttrs GetDTAttrsA GetDTMethods GetDTString GetDTTriggerMethodDataFlags GetDTTriggerMethods GetDefDiskObject "
    "GetDefPrefs GetDefaultPubScreen GetDeviceProc GetDiskFontCtrl GetDiskObject GetDiskObjectNew GetDisplayInfoData GetDrMd "
    "GetExtSprite GetExtSpriteA GetFileSysTask GetGBuffers GetIconRectangle GetIconRectangleA GetIconTagList GetIconTags "
    "GetKey GetLBColumnInfoAttrs GetLBColumnInfoAttrsA GetLanguageSelection GetListBrowserNodeAttrs GetListBrowserNodeAttrsA GetLocaleStr GetMsg "
    "GetNVInfo GetNVList GetOutlinePen GetPlayerAttrs GetPlayerAttrsA GetPrefs GetProgramDir GetProgramName "
    "GetPrompt GetRGB32 GetRGB4 GetRPAttrs GetRPAttrsA GetRadioButtonNodeAttrs GetRadioButtonNodeAttrsA GetRexxBufferFromMsg "
    "GetRexxVar GetRexxVarFromMsg GetScreenData GetScreenDrawInfo GetSpeedButtonNodeAttrs GetSpeedButtonNodeAttrsA GetSprite GetSysTime "
    "GetTagData GetUniqueID GetUnit GetUnitID GetVPModeID GetVar GetVisualInfo GetVisualInfoA "
    "GfxAssociate GfxFree GfxLookUp GfxNew GiveUnit GoodID GoodType HelpControl "
    "HideAllListBrowserChildren HideChooser HideLayer HideListBrowserNodeChildren HideWindow HighlightSetFormat HookEntry HotKey "
    "IDtoStr IEEEDPAbs IEEEDPAcos IEEEDPAdd IEEEDPAsin IEEEDPAtan IEEEDPCeil IEEEDPCmp "
    "IEEEDPCos IEEEDPCosh IEEEDPDiv IEEEDPExp IEEEDPFieee IEEEDPFix IEEEDPFloor IEEEDPFlt "
    "IEEEDPLog IEEEDPLog10 IEEEDPMul IEEEDPNeg IEEEDPPow IEEEDPSin IEEEDPSincos IEEEDPSinh "
    "IEEEDPSqrt IEEEDPSub IEEEDPTan IEEEDPTanh IEEEDPTieee IEEEDPTst IEEESPAbs IEEESPAcos "
    "IEEESPAdd IEEESPAsin IEEESPAtan IEEESPCeil IEEESPCmp IEEESPCos IEEESPCosh IEEESPDiv "
    "IEEESPExp IEEESPFieee IEEESPFix IEEESPFloor IEEESPFlt IEEESPLog IEEESPLog10 IEEESPMul "
    "IEEESPNeg IEEESPPow IEEESPSin IEEESPSincos IEEESPSinh IEEESPSqrt IEEESPSub IEEESPTan "
    "IEEESPTanh IEEESPTieee IEEESPTst INTEGER_GetClass IconControl IconControlA IfAmigaXIP Info "
    "Inhibit InitArea InitBitMap InitCode InitGMasks InitGels InitIFF InitIFFasClip "
    "InitIFFasDOS InitLayers InitMasks InitRastPort InitRequester InitResident InitSemaphore InitStruct "
    "InitTmpRas InitVPort InitView Input Insert InsertCxObj InsertMinNode InstallClipRegion "
    "InstallLayerHook InstallLayerInfoHook InternalLoadSeg InternalUnLoadSeg IntuiTextLength Intuition IntuitionControl IntuitionControlA "
    "InvertKeyMap InvertString IoErr IsAlNum IsAlpha IsCntrl IsDigit IsFileSystem "
    "IsGraph IsInteractive IsLower IsPrint IsPunct IsRexxMsg IsSpace IsUpper "
    "IsXDigit ItemAddress JulianLeapYear JulianMonthDays JulianWeekDay KCmpStr KDoFmt KGetCh "
    "KGetChar KGetNum KMayGetCh KMayGetChar KPrintF KPutCh KPutChar KPutFmt "
    "KPutS KPutStr KVPrintF KillRAD KillRAD0 LABEL_GetClass LAYOUT_GetClass LBAddNode "
    "LBAddNodeA LBEditNode LBEditNodeA LBRemNode LISTBROWSER_GetClass LaunchRexxScript LayerOccluded LayoutIcon "
    "LayoutIconA LayoutLimits LayoutMenuItems LayoutMenuItemsA LayoutMenus LayoutMenusA LendMenus LengthArgstring "
    "LibAllocPooled LibCreatePool LibDeletePool LibDoGadgetMethod LibDoGadgetMethodA LibFreePooled ListBrowserClearAll ListBrowserSelectAll "
    "LoadRGB32 LoadRGB4 LoadSeg LoadView LoadXRef LocalItemData Lock LockAmigaGuideBase "
    "LockDosList LockIBase LockLayer LockLayerInfo LockLayerRom LockLayers LockPubScreen LockPubScreenList "
    "LockRealTime LockRecord LockRecords LockRexxBase MUI_AddClipRegion MUI_AddClipping MUI_AllocAslRequest MUI_AllocAslRequestTags "
    "MUI_AslRequest MUI_AslRequestTags MUI_BeginRefresh MUI_CreateCustomClass MUI_DeleteCustomClass MUI_DisposeObject MUI_EndRefresh MUI_Error "
    "MUI_FreeAslRequest MUI_FreeClass MUI_GetClass MUI_Hide MUI_Layout MUI_LayoutObj MUI_MakeObject MUI_MakeObjectA "
    "MUI_NewObject MUI_NewObjectA MUI_ObtainPen MUI_Offset MUI_Redraw MUI_RejectIDCMP MUI_ReleasePen MUI_RemoveClipRegion "
    "MUI_RemoveClipping MUI_Request MUI_RequestA MUI_RequestIDCMP MUI_SetError MUI_Show MakeClass MakeDosEntry "
    "MakeDosNode MakeFunctions MakeLibrary MakeLink MakeScreen MakeVPort MakeWorkbenchObjectVisible MakeWorkbenchObjectVisibleA "
    "MapANSI MapRawKey MapTags MatchEnd MatchFirst MatchIX MatchNext MatchPattern "
    "MatchPatternNoCase MatchToolValue MaxCli ModeNotAvailable ModifyIDCMP ModifyProp Move MoveLayer "
    "MoveLayerInFrontOf MoveScreen MoveSizeLayer MoveSprite MoveWindow MoveWindowInFrontOf MrgCop NameFromFH "
    "NameFromLock NamedObjectName NewDTObject NewDTObjectA NewDiskObject NewFontContents NewLayerInfo NewList "
    "NewLoadSeg NewLoadSegTagList NewLoadSegTags NewMinList NewModifyProp NewObject NewObjectA NewRegion "
    "NewScaledDiskFont NextConductor NextDisplayInfo NextDosEntry NextObject NextPubScreen NextTagItem ObtainBattSemaphore "
    "ObtainBestPen ObtainBestPenA ObtainCharsetInfo ObtainConfigBinding ObtainDataType ObtainDataTypeA ObtainGIRPort ObtainInfo "
    "ObtainInfoA ObtainPen ObtainQuickVector ObtainSemaphore ObtainSemaphoreList ObtainSemaphoreShared OffGadget OffMenu "
    "OldOpenLibrary OnGadget OnMenu Open OpenAmigaGuide OpenAmigaGuideA OpenAmigaGuideAsync OpenAmigaGuideAsyncA "
    "OpenCatalog OpenCatalogA OpenClipboard OpenDevice OpenDiskFont OpenEngine OpenFont OpenFromLock "
    "OpenIFF OpenIntuition OpenLayoutWindowTagList OpenLayoutWindowTags OpenLibrary OpenLocale OpenMonitor OpenOutlineFont "
    "OpenResource OpenScreen OpenScreenTagList OpenScreenTags OpenWindow OpenWindowTagList OpenWindowTags OpenWorkBench "
    "OpenWorkbenchObject OpenWorkbenchObjectA OrRectRegion OrRegionRegion Output OwnBlitter OwnCard PAGE_GetClass "
    "PALETTE_GetClass PENMAP_GetClass PackBoolTags PackStructureTags ParentChunk ParentDir ParentOfFH ParseDate "
    "ParseIFF ParseIX ParsePattern ParsePatternNoCase PathPart PeekQualifier Permit PointInImage "
    "PolyDraw PopChunk PrintDTObject PrintDTObjectA PrintFault PrintIText Printf Procure "
    "PropChunk PropChunks PubScreenStatus PushChunk PutDefDiskObject PutDiskObject PutErrStr PutIconTagList "
    "PutIconTags PutMsg PutStr QBSBlit QBlit QueryKeys QueryOverscan RADIOBUTTON_GetClass "
    "REQUESTER_GetClass RadioButtons RadioButtonsA RangeRand RawDoFmt RawKeyConvert Read ReadArgs "
    "ReadBattClock ReadBattMem ReadCardStatus ReadChunkBytes ReadChunkRecords ReadEClock ReadExpansionByte ReadExpansionRom "
    "ReadItem ReadJoyPort ReadLink ReadPixel ReadPixelArray8 ReadPixelLine8 ReadUnitID RectFill "
    "RefreshDTObject RefreshDTObjectA RefreshDTObjects RefreshGList RefreshGadgets RefreshPageGadget RefreshTagItemClones RefreshVirtualGadget "
    "RefreshWindowFrame Relabel ReleaseBattSemaphore ReleaseCard ReleaseConfigBinding ReleaseDataType ReleaseGIRPort ReleaseInfo "
    "ReleaseInfoA ReleaseNamedObject ReleasePen ReleaseSemaphore ReleaseSemaphoreList RemAssignList RemConfigDev RemDevice "
    "RemDosEntry RemFont RemHead RemHeadMinList RemIBob RemICRVector RemIntServer RemKBInt "
    "RemLibrary RemMemHandler RemNamedObject RemPort RemResource RemSegment RemSemaphore RemTOF "
    "RemTail RemTailMinList RemTask RemTimerInt RemVBlankInt RemVSprite RemakeDisplay Remove "
    "RemoveAmigaGuideHost RemoveAmigaGuideHostA RemoveAppIcon RemoveAppMenuItem RemoveAppWindow RemoveAppWindowDropZone RemoveClass RemoveCxObj "
    "RemoveDTObject RemoveGList RemoveGadget RemoveMinNode Rename ReplyAmigaGuideMsg ReplyMsg ReplyPkt "
    "ReportMouse ReportMouse1 Request RequestFile ResetBattClock ResetMenuStrip RethinkDisplay RethinkLayout "
    "RethinkVirtualSize RouteCxMsg RunCommand SCROLLER_GetClass SDivMod32 SDivMod64 SKETCHBOARD_GetClass SLIDER_GetClass "
    "SMult32 SMult64 SNPrintf SPACE_GetClass SPAbs SPAcos SPAdd SPAsin "
    "SPAtan SPCeil SPCmp SPCos SPCosh SPDiv SPEEDBAR_GetClass SPExp "
    "SPFieee SPFix SPFloor SPFlt SPLog SPLog10 SPMul SPNeg "
    "SPPow SPSin SPSincos SPSinh SPSqrt SPSub SPTan SPTanh "
    "SPTieee SPTst STRING_GetClass SameDevice SameLock SaveDTObject SaveDTObjectA ScaleGadgetRect "
    "ScaleGadgetRectA ScalerDiv ScanStackToken ScreenDepth ScreenPosition ScreenToBack ScreenToFront ScrollLayer "
    "ScrollRaster ScrollRasterBF ScrollVPort ScrollWindowRaster Seek SelectError SelectInput SelectOutput "
    "SendAmigaGuideCmd SendAmigaGuideCmdA SendAmigaGuideContext SendAmigaGuideContextA SendIO SendPkt SetABPenDrMd SetAPen "
    "SetAmigaGuideAttrs SetAmigaGuideAttrsA SetAmigaGuideContext SetAmigaGuideContextA SetArgStr SetAttrs SetAttrsA SetBPen "
    "SetChipRev SetChooserNodeAttrs SetChooserNodeAttrsA SetClickTabNodeAttrs SetClickTabNodeAttrsA SetCollision SetComment SetConductorState "
    "SetConsoleTask SetCurrentBinding SetCurrentDirName SetCxObjPri SetDMRequest SetDTAttrs SetDTAttrsA SetDefaultPubScreen "
    "SetDesignFont SetDesignFontA SetDiskFontCtrl SetDiskFontCtrlA SetDrMd SetEditHook SetExcept SetFileDate "
    "SetFileSize SetFileSysTask SetFilter SetFilterIX SetFont SetFunction SetGadgetAttrs SetGadgetAttrsA "
    "SetICR SetInfo SetInfoA SetIntVector SetIoErr SetJoyPortAttrs SetJoyPortAttrsA SetKeyMapDefault "
    "SetLBColumnInfoAttrs SetLBColumnInfoAttrsA SetLayerInfoBounds SetListBrowserNodeAttrs SetListBrowserNodeAttrsA SetLocalItemPurge SetMaxPen SetMenuStrip "
    "SetMode SetMouseQueue SetNVProtection SetOutlinePen SetOwner SetPageGadgetAttrs SetPageGadgetAttrsA SetPlayerAttrs "
    "SetPlayerAttrsA SetPointer SetPrefs SetProgramDir SetProgramName SetPrompt SetProtection SetPubScreenModes "
    "SetRGB32 SetRGB32CM SetRGB4 SetRGB4CM SetRPAttrs SetRPAttrsA SetRadioButtonNodeAttrs SetRadioButtonNodeAttrsA "
    "SetRast SetRexxVar SetRexxVarFromMsg SetSR SetSignal SetSoftStyle SetSpeedButtonNodeAttrs SetSpeedButtonNodeAttrsA "
    "SetSuperAttrs SetTaskPri SetTranslate SetVBuf SetVar SetWindowPointer SetWindowPointerA SetWindowTitles "
    "SetWriteMask ShowAllListBrowserChildren ShowChooser ShowLayer ShowListBrowserNodeChildren ShowTitle ShowWindow Signal "
    "SizeLayer SizeWindow SortGList SortLayerCR SplitName StackSwap StartDragSelect StartNotify "
    "StartTimerInt StopChunk StopChunks StopOnExit StopTimerInt StoreItemInContext StoreLocalItem StoreNV "
    "StrConvert StrToDate StrToLong Stricmp StripFont StrnCmp Strncat Strncpy "
    "Strnicmp SubTime SumKickData SumLibrary SuperState Supervisor SwapBitsRastPortClipRect SyncSBitMap "
    "SysReqHandler System SystemControl SystemControlA SystemTagList SystemTags TEXTEDITOR_GetClass TFChangeUnitTagList "
    "TFChangeUnitTags TFEjectMediaTagList TFEjectMediaTags TFExamineFileSize TFFreeUnitData TFGetUnitData TFInsertMediaTagList TFInsertMediaTags "
    "TFStartUnitTagList TFStartUnitTags TFStopUnitTagList TFStopUnitTags TagInArray Text TextExtent TextFit "
    "TextLength ThinLayerInfo TimeDelay TimedDisplayAlert ToLower ToUpper Translate TypeOfMem "
    "UCopperListInit UDivMod32 UDivMod64 UMult32 UMult64 UnGetC UnLoadSeg UnLock "
    "UnLockDosList UnLockRecord UnLockRecords UnlockAmigaGuideBase UnlockIBase UnlockLayer UnlockLayerInfo UnlockLayerRom "
    "UnlockLayers UnlockPubScreen UnlockPubScreenList UnlockRealTime UnlockRexxBase UnpackStructureTags UpdateWorkbench UpfrontLayer "
    "UserState VBeamPos VFPrintf VFWritef VIRTUAL_GetClass VPrintf VSNPrintf Vacate "
    "VideoControl VideoControlTags ViewAddress ViewPortAddress VolumeRequestHook WBInfo WBenchToBack WBenchToFront "
    "WINDOW_GetClass Wait WaitBOVP WaitBlit WaitForChar WaitIO WaitPkt WaitPort "
    "WaitTOF WeighTAMatch WeighTAMatchTags WhichLayer WhichWorkbenchObject WhichWorkbenchObjectA WindowLimits WindowToBack "
    "WindowToFront WorkbenchControl WorkbenchControlA Write WriteBattClock WriteBattMem WriteChars WriteChunkBytes "
    "WriteChunkRecords WriteChunkyPixels WriteDiskFontHeader WriteDiskFontHeaderA WriteExpansionByte WriteFontContents WritePixel WritePixelArray8 "
    "WritePixelLine8 WritePotgo XorRectRegion XorRegionRegion ZipWindow afp arnd cmpstrexec "
    "dbf dgetc dgetch dgetchar dgetnum dprintf dputc dputch "
    "dputchar dputs dputstr fpa fpbcd kgetc kgetch kgetchar "
    "kgetnum kprintf kputc kputch kputchar kputs nnset set "
    "waitbeam ";
    }
};

#endif // AMIGALEXERCPP_H
