@echo off
rem install_stage.bat - stages a clean, install-ready copy of the build
rem output into AmigaED_install\install_src.
rem
rem Called from AmigaED.pro's win32 QMAKE_POST_LINK step as:
rem     cmd /c install_stage.bat "<DESTDIR>" "<INSTALL_SRC_DIR>"
rem
rem Kept as a static file rather than generated by qmake on purpose: the
rem wildcard patterns below (Makefile*, *.rc, *.h, *.*) need to survive
rem intact for robocopy's own parser to see them - living here, in a
rem plain .bat file that only cmd.exe ever reads, they never pass
rem through mingw32-make's own recipe-line shell (which, depending on
rem PATH, may not be cmd.exe - see AmigaED.pro's comments) at all.
rem
rem %~1/%~2 strip any surrounding quotes from the two arguments; the
rem "%1"/"%2" forms below re-quote them for robocopy, so spaces in
rem either path would be handled correctly too (even though neither
rem currently contains any).

set "SRC=%~1"
set "DEST=%~2"

if exist "%DEST%" rmdir /S /Q "%DEST%"
mkdir "%DEST%"

robocopy "%SRC%" "%DEST%" *.* /E /XD release /XF Makefile* .qmake.stash *.rc *.h /NFL /NDL /NJH /NP

rem Also stage the DOC folder (the DE/EN PDF manuals) alongside the built
rem app. Unlike SRC above, this isn't part of the build output (DESTDIR) -
rem it's a static folder that lives next to this .bat file in the project
rem tree, so it's addressed via %~dp0 (this script's own folder) instead
rem of being passed in as an argument. AmigaED_install\AmigaED.iss decides
rem at install time - via its own Yes/No prompt - whether the documentation
rem actually gets copied into the end user's chosen install directory; it
rem just needs to be present here in install_src for that prompt to have
rem something to copy from.
robocopy "%~dp0DOC" "%DEST%\DOC" *.* /E /NFL /NDL /NJH /NP

rem robocopy's exit codes are bit-flags (0-7 = success in various
rem shades, 8+ = real failure) - always report plain success here so
rem the calling recipe line (and mingw32-make) never has to interpret
rem them; robocopy's own console output already shows what happened.
exit /b 0
