/*
 *  File:       schwurbel.h
 *  Purpose:    provides dunctions and Sting-Arrays in
 *              order to schwurbel you die Ohren up!
 *  Version:    1.1.5
 *  Date:       12.01.2024
 *  Author:     Micha B.
 *
 */
 
#include    <exec/types.h>
#include    <exec/libraries.h>
#include    <dos/dos.h>
#include    <dos/dostags.h>
#include    <unistd.h>
#include    <stdlib.h>
#include    <limits.h>

#include	<proto/exec.h>
#include	<proto/dos.h>
#include	<proto/intuition.h>
#include	<proto/utility.h>
 
#define NUM_STRING        128
#define NUM_STRING_LENGTH 256

extern BOOL printLeadIn = TRUE;
extern BOOL myRequest = TRUE;
extern BOOL myDebug = FALSE;      // print debugging information
extern BOOL myClear = TRUE;       // clear output gadget
extern int loops = 10, count = 0; // Auto-Schwurbel repeat values
extern int mydelay = 1;           // Auto-Schwurbel delay
char myPic[512];
 
/* Function Prototype */
extern void busyWait(int secs); 
extern BOOL fileExists(STRPTR fname);

/*
 * Funktion: BOOL fileExists(STRPTR file)
 * Zweck: Prüfe die Existenz einer Datei
 * (UNIX-Style)       
 */
extern BOOL fileExists(STRPTR fname)
{    
    FILE *file;
    
    file = fopen(fname, "r");
    if (file )
    {
        fclose(file);
        return TRUE;
    }
    return FALSE;
}


 
 /* --- Polling delay Function --- */
 extern void busyWait(int secs)
 {
    time_t start_seconds;
    time_t current_seconds;
    
    start_seconds = time (NULL);
    current_seconds = start_seconds;
    if(myDebug)
      printf ("Starting seconds: %d\n", (int)start_seconds);
    
    while( current_seconds < start_seconds + secs) /* busy waiting */
    current_seconds = time (NULL);
    if(myDebug)
      printf("current_seconds = %d\n%d seconds elapsed\n", (int)current_seconds, secs);
 }
 
 
 /* --- einleitende Phrasen --- */
 extern char leadin[][NUM_STRING_LENGTH] = {
    "Es ist doch so:",
    "Die Wahrheit ist:",
    "Was keiner weiß:",
    "Gestern im Buschfunk:",
    "Ja, ja - schon klar:",
    "Die FSK warnt: Dieses Programm ist jugendgefährdend und behauptet Dinge wie dieses:\n",
    "Die FSK warnt: Dieses Programm muss verboten werden! Es stellt wüste Behauptungen wie diese auf:\n",
    "Entgegen anderslautender Meldungen ist es in Wirklichkeit so:",
    "Fakt ist:",
    "Nackte Tatsache:",
    "RT Deutschland warnt:",
    "Die ARGE informiert:",
    "Es stand im 'FOCUS':",
    "Der Bauernverband informiert:",
    "Bernd Höckel gibt bekannt:",
    "Die YouTube-Universität gibt bekannt:",
    "Reichsbürger wissen:",
    "Nicht möglich:",
    "Wichtige Information für Aluhüte:",
    "Wichtige Information:",
    "Laut BND:",
    "Viele wissen es noch nicht:",
    "Hier ist die Wahrheit, die dir verschwiegen wird:",
    "Übrigens:",
    "Das Zentrum für politische Schönheit informiert:",
    "Das Arbeitsamt teilt mit:",
    "Das Ministerium für Inneres teilt mit:",
    "Das Ministerium für Inneres warnt:",
    "Popeye teilt mit:",
    "Sarah Wagenknecht teilt mit:",
    "Catweazle hat es vorhergesagt:",
    "Heiner Lauterbach warnt:",
    "Die ständige Impfkommission warnt:",
    "Der Bundesmineralsekretär warnt:",
    "Lasst euch nix erzählen! Die Wahrheit ist:",
    "Es verhält sich tatsächlich so:",
    "Anders als offiziell behauptet:",
    "Über die wahren Hintergründe werden wir alle belogen:",
    "Glaubt den offiziellen Stellen nicht! Es ist tatsächlich so:",
    "Vertraut nicht auf die Lügenpresse! So war es wirklich:",
    "Die Regierung vertuscht es mal wieder:",
    "Der Deep State will nicht dass du das weißt:",
    "Der Deep State will nicht dass ihr das wisst:",
    "Auch wenn der Bauernverband etwas anderes behauptet - die Wahrheit ist:",
    "Lasst euch nichts anderes weismachen:",
    "Whistleblower fanden heraus:",
    "Wissenschaftlich erwiesen:",
    "Ganz ohne Zweifel:",
    "Was niemand wusste:",
    "Was die Grünen verschweigen:",
    "Was die Ampel verschweigt:",
    "Es geschieht im Verborgenen:",
    "Gestern wurde es bekannt:",
    "Was man dir verschweigt:",
    "Aus sicherer Quelle:",
    "Youtube hat diese Information gelöscht:",
    "Facebook hat diese Information gelöscht:",
    "Was das Fratzenbuch dir vorenthält:",
    "Die sozialen Medien versuchen, es zu verschleiern:",
    "Die Regierung verbirgt es vor dir:",
    "Verschwörung aufgedeckt:",
    "Unmöglich:",
    "Unglaublich:",
    "Unfassbar:",
    "Niemand hat es geahnt:",
    "Bericht aus Berlin:",
    "Deine Mutti will nicht, dass du das weisst:",
    "Deine Mutter hat gesagt:",
    "Braune Blinsen geben bekannt:",
    "Schlagzeile:",
    "Geheimwissen - nicht weitersagen:",
    "Völlig unbemerkt:",
    "Niemand hatte eine Ahnung:",
    "Die Bild-Zeitung deckt auf:",
    "Pressemitteilung:",
    "Schwurbelheimer wissen es längst:",
    "Letzte Meldung:",
    "Latest News:",
    "Schaut genau hin:",
    "Ihr solltet das wissen:",
    "Der Vatikan gibt bekannt:"
 };
 
 /* --- Wer hat was getan? --- */
 extern char openers[][NUM_STRING_LENGTH] = { 
	 "Öko-Terroristen",
	 "Habeck und seine Jünger", 
	 "Chemtrail-Piloten",
	 "Ostgermanische Faschowesen",
	 "Lateinamerikanische Fabelwesen",
	 "Die Grünen", 
	 "Außerirdische",
	 "Pro-russische Spam-Bots",
	 "Flat-Earther",
	 "Demoschafe",
	 "Weiße \"Arier\"",
	 "Der Verein zur Förderung der bierseligen Schwarmdummheit und seine Ortsgruppen",
	 "Die von der dunklen Seite des Mondes",
	 "Die blonde Reichsgruselguste und der Zwerg mit der erlogenen Spritzenattacke",
	 "Die Vögel von der Ampel-Koalition",
	 "Das Schlafschaf-Team aus Berlin und seine AntiFa-Zombies",
	 "Die linken AntiFa-Terroristen",
	 "Sarah Wagenknechts Praktikanten",
	 "Bajuwaren mit 'nem Kropf",
	 "Die Meinungsdikdatur und die Öffentlich-Rechtlichen",
	 "Öko-Stalinisten",
	 "Die in Berlin und Brüssel",
	 "Der Dackelkrawattenträger und die, die die Sonne verklagen will",
	 "Dullies von ganz weit Rechts demonstrierten gegen ein Parteiverbot und",
	 "Die aus der Hafenstraße",
	 "Bedauerliche Einzelfälle aus Sachsen",
	 "Die aus der Roten Flora",
	 "Fernseh-Clowns aus Entenhausen",
	 "Das Ministerium für Überfülle und seine Ministranten",
	 "Der Tugendterror und seine Hintermänner",
	 "Das Schwarz-rote Regime und seine Helfershelfer",
	 "Gutmenschen",
	 "Lauter bedauerliche Einzelfälle aus dem Osten dieser Republik",
	 "Alle meine Entchen",
	 "Bürger aus dem Wilden Osten",
	 "Die Marx Brothers",
	 "Putins Schergen",
	 "Befürworter der Todesstrafe",
	 "Marionetten der Rechten",
	 "Marionetten des Staates",
	 "Die Identitären",
	 "Deine Mutti und ihr Liebhaber",
	 "Rechtspopulisten",
	 "Russische Troll-Fabriken",
	 "Die von der staatlichen Rentenversicherung",
	 "Sprechpuppen aus dem rechten Lager",
	 "Sprechpuppen aus dem linken Lager",
	 "Tanzteekasper mit identitärem Hintergrund",
	 "Die im Staatsfernsehen",
	 "Die Mainstream-Medien",
	 "Die Matrosen der 'Nautilus'",
	 "Bahnhofsklatscher",
	 "Ostdeutsche Broiler",
	 "Figuren wie Alice Weidel",
	 "Figuren wie Angela Merkel",
	 "Technokratische Politiker",
	 "Russische Truppen",
	 "Facebook-Nutzer",
	 "Dullies aus Rendsburg",
	 "Blitzbirnen auf Facebook",
	 "Kreise um Elon Musk",
	 "Die aus den GEZ-Propagandasendungen",
	 "Der Multikultiwahn und seine Claqueure",
	 "Bauernfänger",
	 "Die Schergen der Mickymaus",
	 "Die Impflügner",
	 "\"Ampel weg!\"-Schreier",
	 "Die Schnapsdrosseln aus Brownunder",
	 "Der Zentralrat der Fliesentischbesitzer und seine Helfershelfer",
	 "Bill Gates und seine Freunde",
	 "Die vielen Impftoten",
	 "Der Islam und seine Spielarten",
	 "Landwirte",
	 "Schlafschafe wie du",
	 "Harte Hunde",
	 "Tierschützer",
	 "Hobbyjäger",
	 "Schreihälse",
	 "Schreihalstierschützer",
	 "Verstrahlte Nullnummern",
	 "Verstrahlte Nullnummern aus der bürgerlichen Mitte",
	 "Die Dödel von der neurechte Avantgarde",
	 "Die von der identitären Bewegung",
	 "Martin Sellner und seine Kumpel",
	 "Markus Söder und seine Spezl",
	 "Bangemacher der Werte-Union",
	 "Die Echsenmenschen",
	 "Agrar-Terroristen",
	 "Zigeunerschnitzel",
	 "Amiga-Fans",
	 "Oberbayrische G'schaftlhuber",
	 "Faschos mit reziprok entwickelten Geschlechtsteilen",
	 "Die da oben",
	 "SUV-Fahrer",
	 "Rechtsideologische Kettenhunde",
	 "Der kleine Kerl aus Österreich und seine Verehrer",
	 "Bielefelder Bürger",
	 "Die linksgrün-versifften Realitätsverweigerer",
	 "Alice Weibel und Bernd Höckel",
	 "Hinterbänkler",
	 "Hinterbänkler aus den Reihen der AfD",
	 "Bellatrix vom Storch und ihre Brut",
	 "Heiner Lauterbach und seine Clique von gekauften Lügenbolden",
	 "Bundeswehr und Polizei",
	 "Gandalf und die sieben Zwerge",
	 "Krude Dummschwaller",
	 "Ewig Gestrige",
	 "Die Rechtschreibreform und PISA",
	 "Der Bauernverband und seine Trecker-Terroristen",
	 "Der Amtsschimmel und seine Reiter",
	 "Dullies mit 'nem Trecker",
	 "Asylbewerber",
	 "Das Dauerempörium und seine Knechte",
	 "Papiertiger",
	 "Drama-Queens",
	 "Auslandsdeutsche",
	 "Faschos",
	 "Alle möglichen Leute", 
	 "Alle Völker der Erde",
	 "Arbeitsunwillige Dauerstudenten",
	 "Apparatschiks der BRD GmbH",
	 "Baerbock und Konsorten",
	 "Veganer",
	 "FDP'ler",
	 "CDU'ler",
	 "SPD'ler",
	 "Teletubbies",
	 "Schwule und Lesben",
	 "Die Fans von Till Lindemann",
	 "Fans von Oliver Pocher",
	 "Fritzchen und Erna",
	 "Der liebe Gott und die himmlischen Heerscharen",
	 "Omnivoren",
	 "Die vom rechten Rand",
	 "Angestellte der BRD GmbH",
	 "Diplom-Krawaller",
	 "Klima-Kleber",
	 "Kriegsdienstverweigerer",
	 "Grenztruppen der DDR",
	 "Reichsbürger",
	 "Verfassungsfeinde",
	 "Andersdenkende",
	 "Reptiloide",
	 "Der Neoliberalismus und seine Schergen",
	 "Die Arbeitsgruppen Genderfreunde und Muslime in der AfD",
	 "Die Grünen",
	 "AfD'ler",
	 "Ketzer",
	 "Doitsche Kartoffeln",
	 "Maskenverweigerer",
	 "Corona-Leugner",
	 "Baumschüler",
	 "Schwurbler",
	 "Rechtsradikale",
	 "Bio-Deutsche",
	 "Die aus der AfD-Parteizentrale",
	 "Q-Anon Fans",
	 "Landesverräter",
	 "Akten-Dullies",
	 "Lüsterne Hausfrauen",
	 "Linke Störenfriede",
	 "Subfontanell spärlich moblierte Doldis",
	 "Rechte Störenfriede",
	 "Freiwillige Helfer der Grenztruppen",
	 "Freiwillige Helfer der Volkspolizei",
	 "Weiße Hinterwäldler",
	 "Aalglatte Polit-Karriereristen",
	 "Abstoßende Typen aus Braunhausen",
	 "Abtreibungsgegner",
	 "Abtrünnige Kleinstadtbewohner",
	 "Aktenkundige Tatsachenverdreher",
	 "Biodoitsche Neofaschisten",
	 "Linksideologische Anstandswauwaus",
	 "Die Mehrzahl der Doofen",
	 "Brian und die judäische Volksfront"
 };
 
 /* --- Tätigkeiten --- */
 extern char dowords[][NUM_STRING_LENGTH] = {
	 "verursachen",
	 "bringen",
	 "haben",
	 "sind",
	 "verbieten",
	 "leugnen",
	 "kaufen",
	 "verkaufen",
	 "lieben",
	 "hassen",
	 "brauchen",
	 "verneinen",
	 "bestreiten",
	 "leiden an",
	 "verantworten",
	 "wurden im Bordell erwischt und verlangen jetzt",
	 "fordern",
	 "verlangen",
	 "bevorzugen",
	 "sind die Auslöser von",
	 "sind verantwortlich für",	 
	 "sorgen für",
	 "träumen von",
	 "waren im Think-Tank und entdeckten",
	 "werben für Menschenketten und wünschen sich",
	 "fallen auf Spam-Bots rein und schreien nach",
	 "trafen sich konspirativ in Potsdam und sprachen über",
	 "hatten ein konspiratives Meeting und beschlossen",
	 "wollten den Reichstag stürmen und haben",
	 "wollten den Reichstag stürmen und verlangen",
	 "wollten das Kapitol stürmen und haben",
	 "wollen eine Partei gründen und stehen für",
	 "haben deinen Hund gevögelt und sind",
	 "haben deinen Bruder geschändet und sind",
	 "haben deine Schwester geschwängert und sind",
	 "haben deine Katze gegessen und wollen nun",
	 "haben deine Vettern beleidigt und sind",
	 "haben Martin Rütter mit deiner Dressur beauftragt und wollen",
	 "demonstrierten gegen ein Verbot und verlangten",
	 "wollen deinen Hamster essen und haben",
	 "wollen deinen Goldfisch braten und haben",
	 "lachen über deine Nudel und wollen",
	 "werden durch die Existenz deiner Mutter beleidigt und sind",
	 "haben deine Oma verprügelt und sind",
	 "glauben jeden Schwachsinn und haben",
	 "sind der Sitzung fern geblieben und verlangen nun dafür",
	 "stammen aus Mordor und wollen",
	 "haben mir die Unschuld geraubt und wollen",
	 "waren auf einer Party der LGBTQ-Community und es gab",
	 "werden von der AntiFa bezahlt und sind",
	 "katalysieren",
	 "wurden von Trump gekauft und sind",
	 "besuchten das Restaurant am Ende der Galaxis und verlangten",
	 "haben keine Ehre und sind",
	 "verpflichteten Greta Thunberg für deine Umerziehung und wollen",
	 "verkaufen sich an",
	 "erschlichen sich",
	 "verrieten",
	 "klauten",
	 "begünstigen",
	 "ermöglichen",
	 "stahlen",
	 "verlangen",
	 "scheißen auf",
	 "entwendeten",
	 "stehlen für",
	 "schaffen",
	 "schufen"
 };
 
 /* --- was wurde getan / was wurde ausgelöst? --- */
 extern char descriptions[][NUM_STRING_LENGTH] = {
	 "globale Hungersnöte",
	 "antiimperialistische Solidarität",
	 "Kondensstreifen am Himmel",
	 "unaufhaltsame Flüchtlingsströme",
	 "Wirtschaftsflüchtlinge",
	 "klare Kante",
	 "harte Drogen",
	 "Willkommenskultur",
	 "Das Zentrum für politische Schönheit",
	 "Freiheit",
	 "gleichgeschlechtliche Liebe",
	 "Inzucht",
	 "schreiende Kamele",
	 "ein Toupet in blond",
	 "die Tourenbusse der AntiFa",
	 "einen Ödipus-Komplex",
	 "Keuchheit vor dem Feind",
	 "Krawall im Land",
	 "die Konterrevolution",
	 "eine Bootsfahrt durch das Mittelmeer",
	 "gebratene Goldhamster",
	 "frittierten Goldfisch",
	 "Döner",
	 "Dosenbier",
	 "einen Vollrausch",
	 "ein Verbot der AfD",
	 "Mindesthirn",
	 "AfD-Fanpost",
	 "einen kleinen Pimmel",
	 "Bauernopfer",
	 "Greta Thunberg",
	 "auf die Glocke",
	 "Hefezöpfe",
	 "frisch gebackenes Brot",
	 "keine Nazis",
	 "kleine Nazis",
	 "Falafel",
	 "GEZ-Gebühren",
	 "Marihuana auf Rezept",
	 "Klimakleber",
	 "Lamentiergeräte",
	 "linksgrünversiffte Gutnazis",
	 "Remigration",
	 "Coitus interruptus",
	 "Jammer-Ossis",
	 "ein Dilemma",
	 "cerebrale Flatulenzen",
	 "Sprechdurchfall",
	 "Freihandelsabkommen",
	 "russische Spam-Bots",
	 "Kopftuchmädchen",
	 "alimentierte Messermänner",
	 "Rassenschande",
	 "Kopulation",
	 "Geschlechtsverkehr",
	 "Geschlechtskrankheiten",
	 "eine schmerzhafte Dauererektion",
	 "ein dispensationalistisches Endzeitszenario",
	 "was aufs Maul",
	 "die Hosen voll",
	 "die Agrarrevolution",
	 "tendentielle Gefahr für die Pressefreiheit",
	 "Olaf Scholz",
	 "Frauke Petry",
	 "Alice Weidel",
	 "ausgestreckte rechte Arme",
	 "ein Verbrennerverbot",
	 "Lederhosen",
	 "Witzfiguren",
	 "Rechtsaußen",
	 "die Auflösung des Freistaates Bayern",
	 "den surrealen Expressionismus",
	 "Reptiloide",
	 "Schwarmwissen",
	 "Schwarmdummheit",
	 "Würstchen mit Senf",
	 "Echsenmenschen",
	 "den Prager Frühling",
	 "Asylbetrüger",
	 "Massenvertreibung",
	 "Deportation",
	 "große Trübsal",
	 "Westgeld",
	 "Chemtrail-Piloten",
	 "Sozialschmarotzer",
	 "rassistische Sprüche",
	 "Überfremdung",
	 "radikale Höflichkeit",
	 "linke Drecksäcke",
	 "linke Sausäcke",
	 "rechte Sausäcke",
	 "rechte Drecksäcke",
	 "Paste-and-Copy-Wissenschaften",
	 "wandernde Berufsdemonstranten",
	 "bezahlte Demo-Touristen",
	 "Backpfeifen",
	 "systemhörige Reklamesklaven",
	 "systemhörige Regimesklaven",
	 "braun-blaue Regimesklaven",  
	 "braun-blaue Reklamesklaven", 
	 "regimetreue Speichellecker",
	 "die neue Räterepublik",
	 "die bürgerliche Mitte",
	 "die Existenz von Bielefeld",
	 "den Deep State",
	 "Omnipotenz",
	 "Weltoffenheit",
	 "Meinungsfreiheit",
	 "Artensterben",
	 "Leonardo di Carpaccio",
	 "Pegida",
	 "Kräuterfrikadellen",
	 "Klüngelkapitalismus",
	 "eine unheilige Allianz",
	 "Korrektheitsterror",
	 "Reichsflugscheiben",
	 "L. Ron Hubbard",
	 "Freakadellen",
	 "eine Staatsaffäre",
	 "Streifenhörnchen",
	 "Katzenscheiße",
	 "Hühnerkacke",
	 "Arbeitskräftemangel",
	 "Fachkräftemangel",
	 "Chem-Trails",
	 "Morgellons",
	 "Kopfschmerzen",
	 "Glasnost",
	 "Perestroika",
	 "Anlass zu Misstrauen",
	 "blau-braune Schlümpfe",
	 "feuchte Träume im Wasserbett",
	 "den Wiederaufbau der Mauer",
	 "Überfremdung",
	 "Altersdiskriminierung",
	 "rechten Terror",
	 "linken Terror",	 
	 "öffentliche Mittel",
	 "Nahverkehr",
	 "Pogrome",
	 "Sturmtruppen",
	 "Schlägertrupps",
	 "Toastbrot",
	 "Wutbürgistan rechts der Mitte",
	 "Ratatouille",
	 "syphilitische Ausfallerscheinungen",
	 "cerebrovasculäre Kurzatmigkeit",
	 "eine Schädelleeraufnahme",
	 "Bärendienste",
	 "Papiertiger",
	 "Fake News",
	 "Krapfen mit Senf",
	 "schwedische Gardinen",
	 "den Arbeiter- und Bauernstaat",
	 "die Nazi-Keule",
	 "Trecker-Vergeltungsmaßnahmen",
	 "die Arbeiter-und-Bauern-Inspektion",
	 "frisch geschlachtetes Tofutier",
	 "Würstel aus Fleischersatz",
	 "Lactose-Intoleranz",
	 "ein dauerempörtes Nichts",
	 "Miettoiletten",
	 "ideologische Sättigungsbeilagen",
	 "Fleischersatzprodukte",
	 "allgemein geltende Meinungen",
	 "die Sintflut",
	 "Volksfahrräder",
	 "Lattenroste",
	 "den Umsturz",
	 "Feuchtgebiete",
	 "den Untergang der Titanic",
	 "Schluckspechte",
	 "Schwurb-Lo-Mat",
	 "Klosterfrau Melissengeist",
	 "Sodom und Gomorrha",
	 "Verunsicherung",
	 "verruchte Bardamen",
	 "Abwrackprämie",
	 "Maultrommeln",
	 "Freibier",
	 "Präservative",
	 "eine Kneipenschlägerei",
	 "Viagra",
	 "blaue Pillen",
	 "Atomkraftgegner",
	 "käufliche AfD-Sprechpuppen",
	 "Geschichtsrevisionismus",
	 "verweichlichte Jammerlappen",
	 "Bausoldaten",
	 "Thälmannpioniere",
	 "Volkspervertierung",
	 "Abschaum",
	 "Teletubbies",
	 "die Ächtung der Jagd",
	 "die Abschöpfung der Kaufkraft",
	 "aggressive Absatzmethoden",
	 "Morgenlatten",
	 "Analsex",
	 "Kloschüsseln aus Gold",
	 "Asyltourismus",
	 "deutsche Leitkultur",
	 "Volkskultur",
	 "Atomkraft"	 
 };
 
 extern char closers[][NUM_STRING_LENGTH] = {
	"Ich sag' ja nur, was die schweigende Mehrheit denkt.",
	"Wenn das so weitergeht, muss ich bald arabisch lernen.",
	"Endlich einer, der die Wahrheit ausspricht!",
	"Das wird man doch noch sagen dürfen?",
	"Lügenkresse!",
	"Lügenpresse!",
	"Glasmost!",
	"Schwurb-Lo-Mat gehört verboten!",
	"Soschel Mierda!",
	"Staatspropaganda vom Feinsten!",
	"Ich habe ein starkes Immunsystem, da brauch ich keine Impfung.",
	"Na, zieht´s im Hirn?",
	"Daran verdient nur die Pharma-Industrie!",
	"Die Zahlen sind nur so hoch, weil so viel getestet wurde.",
	"Das sind moderne Bio-Waffen.",
	"Wir sind mehr!",
	"Du Propaganda-Opfer!",
	"Schlafschaf!",
	"Nazis essen heimlich Falafel.",
	"Ob und wie man kommunizieren kann, hängt immer vom Kontext ab.",
	"Gesunde werden diskriminiert.",
	"Deutschland ist eine Diktatur!",
	"Wann kommt das Umdenken?",
	"Winselpinsel!",
	"Wer unbedingt stolz auf sein Volk sein will, der sollte Imker werden.",
	"Wenn die Erde eine Scheibe wäre, dann würdest Du am rechten Rand runterfallen.",
	"Als ob ich nicht schon genug Probleme hätte!",
	"Wacht endlich auf, Ihr Schlafschafe!",
	"Das führt zur Zerstörung von Deutschland!",
	"Wer was dagegen sagt, wird in die rechte Ecke gestellt.",
	"Ich bin das Opfer!",
	"Nicht Alles war schlecht in den Dreissigerjahren.",
	"Ich bin ja kein Nazi - aber das wird man in diesem Land ja wohl noch sagen dürfen!",
	"Ihr stilisiert euch medienwirksam zu Opfern der Vergangenheit.",
	"Deutsches Kulturgut muss erhalten bleiben!",
	"Christliche Werte sind wichtig!",
	"Wir sind das Volk!",
	"Deutschland ist noch besetzt!",
	"Hitler hat nix falsch gemacht.",
	"Ich kann nicht rechts sein - ich habe ausländische Freunde.",
	"Nie wieder ist jetzt.",
	"Denk da bitte nochmal drüber nach!",
	"Abwechslung macht das Leben süß.",
	"Du musst meine Intoleranz tolerieren!",
	"Du wirst als Hetero-Mann diskriminiert.",
	"Muss man sich einen Rock anziehen, um hier nicht diskriminiert zu werden!?",
	"Ja sind wir hier in Takatukaland?",
	"All die schmutzigen Details kann man auf Facebook nachlesen.",
	"!!!drölf88!1111!0815!!!",
	"Politiker lieben Phrasen.",
	"Ich bin für die Prokdatur des Dilletariats.",
	"Merk dir das gefälligst!",
	"Abseits ist, wenn der Schiedsrichter pfeift.",
	"Alles zum Wohle des Volkes!",
	"Ihr habt mein volles Vertrauen.",
	"Wir verlangen schonungslose Aufarbeitung!",
	"Wir verlangen schonungslose Aufklärung!",
	"Abwesende haben immer unrecht!",
	"Vögel wie du sind nichts weiter als der rosa Elefant im Raum.",
	"Das hat man doch schon immer gewusst!",
	"Wer das nicht weiß, ist ein realitätsverlorenes Schlafschaf!",
	"Wehe, wenn wir Euch kriegen!",
	"Du akrobatischer Volkstänzer, Sie!",
	"Bitte stell' noch heute deinen Ausreiseantrag, du Flachpfeife!",
	"Dafür werden sie allesamt an die Wand gestellt.",
	"Sobald wir die Macht übernommen haben, sind sie alle fällig.",
	"Keine Gnade.",
	"Das Kamel schreit. Die Karawane zieht weiter.",
	"Sator Arepo Tenet Opera Rotas!",
	"Wenn du nacher zum Lachen in den Keller gehst, bring Bier mit rauf!",
	"All dieser Quatsch von wegen der politischen Korrektheit...",
	"Ich gendere nicht - ich habe Deutsch gelernt!",	
	"Im Mittelpunkt steht der Mensch.",
	"Von allen Dingen, die du verloren hast, vermisst du sicher deinen Verstand am meisten?",
	"Nur ein Fliegenschiss im Verlauf der Geschichte.",
	"Das Boot ist voll!",
	"Alle Angaben ohne Gewähr.",
	"Die Dummheit wohnt inzwischen überall und hat aufgehört, sich zu schämen.",
	"Sowas braucht man so nötig wie 'nen Kropf!",
	"Absolut alles ist verloren!",
	"Was wahr ist, muss wahr bleiben!",
	"Da beisst die Maus keinen Faden ab!",
	"Das war schon immer so und das bleibt auch so!!!",
	"Geh doch nach drüben, wenn's Dir hier nicht passt!",
	"Alles Nestbeschmutzer!",
	"Nützt ja nix, weisst ja wie's is.",
	"Ich habe das genauestens auf YouTube recherchiert!",
	"Das kann man doch jeden Tag auf Facebook lesen!",
	"Meine Stammtischbrüder denken das auch!",
	"Bist Du für den Frieden?",
	"Frag doch mal die Maus!",
	"Fragen Sie Frau Erika.",
	"Winke-Winke!",
	"Ihr perversen Irren trinkt doch Kinderblut!",
	"Die Welt ist erkennbar.",
	"Nicht zu glauben, was Du alles glaubst!",
	"Eure Schaukeln standen eindeutig zu dicht an der Wand, ihr Luschen!",
	"Ihr wohnt wohl im Tal der Ahnungslosen?",
	"Ewige Freundschaft mit der ruhmreichen Sowjetunion!",
	"Ein deutscher Mann weiß, was da zu tun ist!",
	"Wir sind die Sieger der Geschichte!",
	"Haltet mich bloß nicht für einen Nazi. Ich bin Patriot!",
	"Ein bedauerlicher Einzelfall.",
	"Die Ukraine ist die Laborsituation deutscher Waffenschmieden.",
	"Papiertiger!",
	"Nicht alles, was für den Arsch ist, ist ein Fieberthermometer.",
	"Wenn die Guten nicht kämpfen, siegen die Schlechten.",
	"Wo bleibt die internationale Solidarität?",
	"Das ist nicht nur in Deutschland so!",
	"Das ist Karma, Baby!",
	"Wenn der Kuchen spricht haben die Krümel Pause, Du Spacken!",
	"Ein Wortschatz wie ein Waffenschrank!",
	"Scheißt ein Bär in den Wald?",
	"Schweig, du Aktendulli!",
	"Wir werden alle überwacht.",
	"Deine Genossen werden das nicht mögen.",
	"Du hast dir ja wohl den Kopf gestoßen?",
	"Schreib dir das ins Muttiheft!",
	"Aber solche wie du wissen es natürlich besser.",
	"Eine kleine flotte Biene ist die Teppichkehrmaschine!",
	"Abendrot verspricht dem Bauern Lohn und Brot, dahingegen Morgenröte verheißt dem Bauern arge Nöte.",
	"Ach, deine Augen droh'n mir mehr Gefahr als zwanzig ihrer Schwerter. Blickst du mich aber freundlich an, so bin ich gegen ihre Rachsucht gestählt.",
	"Aber ich bin für die Leute deswegen kein anderer Mensch.",
	"Aber davon war doch nie die Rede!",
	"Aber wie wird sie aussehen, die Zukunft für junge Menschen in Deutschland?",
	"Aber alle sind ein wenig stolz auf das, was sie geleistet haben.",
	"Das ist ein abgekartetes Spiel!",
	"Du musst abrupt mit deinen Drogen aufhören!",
	"Ach, hör uff!",
	"Ich werd' dann mal achselzuckend zur Tagesordnung übergehen.",
	"Achten Sie auf die Details!",
	"Adi Dassler ließ sich das als Warenzeichen eintragen.",
	"Alle Teilnehmer bekommen eine Medaille.",
	"Alle Probleme der Welt lassen sich nicht lösen.",
	"Alle lügen wie gedruckt.",
	"Alle Menschen in der Stadt kennen dich...",
	"Alle Bürger unterstehen dem Gesetz.",
	"Alle hassen Dich!",
	"Im Anhang finden Sie ein Dokument.",
	"Das darf nicht hingenommen werden!",
	"Alle Leute reden über dich...",
	"Wo in aller Welt hast du da wieder gesteckt?", 
	"Die Hölle ist leer und alle Teufel sind hier.",
	"In allem Schlechten liegt das Gute im Ansatz schon verborgen.",
	"Als ich noch an der Uni war, haben wir auch immer gekifft.",
	"Aller Anfang ist schwer.",
	"Allein der Aktienkurs, der um rund 8 Prozent gesunken ist, trübt die positive Bilanz.",
	"Alles senkrecht?",
	"Alles oder nix!",
	"Alte Gewohnheiten lassen sich schwer ablegen.",
	"Alles was ich über Moral und die Pflichten der Menschen weiß, verdanke ich dem Fußball.",
	"Alles ist besser als diese Lösung.",
	"Alles ist besser als geopfert zu werden.",
	"Alles in Ordnung.",
	"Alles in allem ist das ein sehr gut lesbares Buch über ein nicht ganz leichtes Thema.",
	"Alles hat einmal ein Ende.",
	"Alles geschieht aus einem bestimmten Grund.",
	"Alles wird gut!",
	"Alles Denken ist unmoralisch. Sein eigentliches Wesen ist Zerstörung. Wenn Sie über etwas nachdenken, töten Sie es.",
	"Als das Telefon läutete, rutschte mir das Herz in die Hose. Ich wusste, es gab schlechte Nachrichten.",
	"Oh, alles wird zum Genuß, wenn man es zu oft tut.",
	"Alles wie immer!",
	"Altes Brauchtum geht verloren!",
	"Andere kochen auch nur mit Wasser.",
	"Änderungen vorbehalten!",
	"Alles im grünen Bereich.",
	"Selbst Ärzten wird oft vorgeworfen, nicht sehr mitteilsam zu sein.",
	"Atomenergie ist sehr gefährlich...",
	"Du konsumierst offenbar blaues Badesalz?",
	"Auch Rom wurde nicht an einem Tage erbaut.",
	"Auch bei einem Fehlschlag der Verhandlungen muss die Türkei fest in den europäischen Strukturen verankert werden.",
	"Auch dem Teufel muss man sein Recht lassen.",
	"Auch ein blindes Huhn findet mal 'nen Korn.",
	"Auch eine kaputte Uhr geht zweimal am Tag richtig.",
	"Auch dem Aufmerksamsten entgeht manchmal etwas.",
	"Auf der Hochzeit waren prominente Gäste dünn gesät.",
	"Auf den Bergen liegt viel Schnee.",
	"Auf Rang zwei und drei folgen die USA und Großbritannien, danach die Schweiz, Italien und Frankreich.",
	"Auf welche Art habt ihr euch kennengelernt?",
	"Auf sie mit Gebrüll!",
	"Auf Grund dessen muss ich ablehnen.",
	"Auf knapp zwei Einwohner kommt im Schnitt ein PKW.",
	"Auf die Erstbestellung gewähren wir einen Rabatt von 15\%",
	"Auf so einen Handel würde ich mich nie einlassen!",
	"Auf gut Wetter vertrau', beginnt der Tag nebelgrau.",
	"Auf eine gute Zusammenarbeit!",
	"Auf den Tisch gehört der Kuchen, da haben die Füße nichts zu suchen!",
	"Auf die Ergreifung der Täter stehen 25 000 Euro Belohnung.",
	"Auf Sittenverfall folgt Verbrechen!",
	"Auf meinem Gesicht macht sich ein Grinsen breit.",
	"Auf dem Foto ist deine Mutter zu sehen.",
	"Auf einem Bein kann man nicht stehen.",
	"Die liegen jetzt auf der Intensivstation.",
	"Auf welchem Deck ist hier eigentlich die Bar?",
	"Auf Ersuchen eines Kunden wurde der letzte Passus gestrichen.",
	"Auf ein Wort, Herr Scholz!",
	"Findet Nemo!",
	"Rechte Rüben unterpflügen!",
	"Auf eine konkrete Frage erwarte ich auch eine konkrete Antwort!",
	"Auf seinem eigenen Mist kräht der Hahn am lautesten.",
	"Auf deine privaten Angelegenheiten in aller Öffentlichkeit anzuspielen war unfair!",
	"Auf ein williges Pferd legen alle ihre Last.",
	"Auf dass alle guten Nachrichten vor uns und alle schlechten Nachrichten hinter uns liegen!",
	"Auf so etwas muss man immer gefasst sein.",
	"Dafür kann man ja wohl Aufmerksamkeit verlangen!",
	"Augenblicklich sind sie beim Einkaufen.",
	"Augenblicklich ist es mucksmäuschenstill im Saal.",
	"Aus welcher Region in Italien kommst du?",
	"Aus welchem Teil in China kommst du?",
	"Das kann man ja wohl aus dem Kaffeesatz lesen!",
	"Aus einem Buch abzuschreiben, ist Plagiat, aus zehn Büchern abzuschreiben, ist Forschung.",
	"Alles Fakten!",
	"Alles Fakten. Ich sage das ja nicht aus lauter Jux und Tollerei!",
	"Aus lauter Jux und Tollerei.",
	"Aus dem Alter müsstest du ja wohl heraus sein!",
	"Aus Kindern werden Leute.",
	"Aus Alt mach Neu.",
	"Aus welcher Zeit stammt dieser Artefakt?",
	"Canabisiert Legalis!",
	"Aus einem Kieselstein kann man keinen Diamanten schleifen.",
	"Aus nichts wird nichts.",
	"Wer jetzt nicht aufsteht, der hat nix verstanden.",
	"Rapunzel, Rapunzel! Lass' dein Schamhaar herunter!",
	"Das AfD Parteiprogramm ist ein nutzloses Muster ohne Wert. Das Papier ist weder saugfähig noch perforiert.",
	"Aus irgendeinem Grund funktioniert mein Computer nicht mehr.",
	"Aus diesem Grund gehe ich inzwischen regelmäßig ins Fitnessstudio!",
	"Das ist doch sicher aus der Luft gegriffen!",
	"Da macht jemand aus einer Mücke einen Elefanten!",
	"Da macht jemand aus einem Elefanten eine Mücke!",
	"Aus freien Stücken kannst du das natürlich wieder mal nicht akzeptieren.",
	"The white zone is for loading and unloading only...",
	"Darauf einen Düchardeng!",
	"Solange es im Internet steht, ist es geheim genug. Du weißt aber auch garnix!",
	"Im Ausland richtet man sich nach den örtlichen Gepflogenheiten, das kann man ja wohl verlangen!",
	"Die Regierung quetscht uns aus wie Zitronen!",
	"Die Rechten wollen uns alle für dumm verkaufen",
	"Außer, wenn du krank bist.",
	"Salbei! Dalbei! Adomai!",
	"Außer mir war keiner da.",
	"Außer einem sind alle anwesend.",
	"Außer Spesen nichts gewesen.",
	"Hast du überhaupt schon mal Nahverkehr gehabt?",
	"Die Preise werden strukturell steigen.",
	"Jetzt können wir herausfinden, was wir an Stelle unserer Großeltern getan hätten.",
	"Ich habe es kommen sehen: Breit aufgestellt nach Schulterschluss - Wagenknecht koaliert mit sich selbst.",
	"Zu außergewöhnlich hohen Preisen.",
	"Ich bewundere dich für deine Unterstützung! Für mich bist du wie der Held aus Sophokles' bekannter Tragödie!",
	"Außerst vertrauliche Information!",
	"Wenn das so weitergeht werde ich mir einen neuen Computer kaufen.",
	"Bald ist die Kacke am Dampfen.",
	"Wer sich in die Bar begibt geht darin um.",
	"Wer sich in Gefahr begibt kommt darin um",
	"Beachten Sie das bitte bei zukünftigen Gelegenheiten!",
	"Beachten Sie bitte bei allen Angeboten das Ablaufdatum.",
	"Bedauere, dieser Platz ist besetzt.",
	"Bedeutet, dass militärische Einstellungsregeln bewusst unklar gelassen werden, um Soldaten weitgehend vor Strafverfolgung zu schützen.",
	"Bedienung - setzen Sie Ihren Arsch in Bewegung!",
	"Wo befindet sich die Bar?",
	"Ich trinke meinen Kaffee schwarz - nicht braun.",
	"Du hast doch 'n Bahlsen-Syndrom!",
	"Was ist das Blöde an der AfD? Genau: Ihre Wähler!",
	"Du begehst den selben Fehler jedes Mal wieder.",
	"Sie werden dich kriegen!",
	"Zu Beginn des Monats wird mehr Miete fällig.",
	"Behalten Sie bitte ein unterschriebenes Exemplar als Beleg für ihre Unterlagen.",
	"Behandelt eure Kinder mit Respekt!",
	"Am Gleis 7 ist heute kein Picknick möglich.",
	"Wir dürfen jetzt den Kopf nicht in den Sand stecken.",
	"Wir dürfen jetzt den Sand nicht in den Kopf stecken.",
	"Beherrschen Sie sich!",
	"Habt mal Arsch in der Hose!",
	"Wie unfair, David!",
	"Beherrschst du das Einmaleins?",
	"Bei ihrem Schicksal muss man einfach mitleiden.",
	"Bei dir ist das Glas immer halb leer.",
	"Facebook ist wie Urlaub - man kann anderen beim braun werden zusehen.",
	"Da ist doch eine Gehaltserhöhung fällig!",
	"Seltsam - aber so steht es geschrieben.",
	"Da wird der Hund in der Pfanne verrückt.",
	"Jeder hat irgend eine Leiche im Keller.",
	"Bei zwei von ihnen stellte sich heraus, dass sie familiäre Probleme hatten.",
	"Bei dem Fest kamen viele Menschen zusammen.",
	"Murphy's Gesetz!",
	"Bei null Grad gefriert das Wasser.",
	"Da kann man ruhig schon mal Danke sagen.",
	"Immer ruhig und sachlich bleiben!",
	"Quelle: Mossad",
	"Die Erde ist eine Scheibe - und du treibst ganz am Rand...",
	"Hitlers Virus lebt.",
	"Bei Hitlers brennt noch Licht",
	"Lasst euch nicht von Nazis quälen, geht beim nächsten Mal zum Wählen!",
	"Wie schrecklich, dass man sterblich ist und alles sonst gewerblich ist!",
	"Lügen haben kurze Beine.",
	"Lügen haben kurze Beine - und du bist ja auch nicht grad groß gewachsen.",
	"Rot scheint die Morgensonne!",
	"Du bekommst dein Gehalt doch in Sanifer-Bons ausgezahlt?",
	"Bielefeld existiert.",
	"Bielefeld existiert gar nicht!",
	"Nachdem jemand in Sachsen entdeckt hat, dass es in der ganzen Bude stinkt, wenn man ins Wohnzimmer kackt, wird jetzt untersucht, ob das in Niedersachsen genauso ist.",
	"Hunger wurde nur erfunden, um die Lebensmittelindustrie zu pushen.",
	"Nur die allerdümmsten Kälber wählen ihre Metzger selber.",
	"Wer ist das Volk?",
	"Nitrolack ist kein Getränk.",
	"Brüder, zur Sonne, zur Freizeit!",
	"Die sind mit allen Wassern gewaschen.",
	"Mein Name ist Hase. Ich weiß von nichts.",
	"Lügenpresse?",
	"Wie bei Hempels unter'm Sofa...",
	"Die reden doch wieder mal nur um den heißen Brei herum!",
	"In dieser Angelegenheit kann ihnen niemand das Wasser reichen.",
	"Geht's noch?",
	"Grzimek hätte bestimmt noch einen Platz für dich.",
	"Serengeti darf nicht sterben.",
	"Da sollten wir alle aber mal kräftig Danke sagen!",
	"Die Kritik an anderene hat noch keinem die eigene Leistung erspart.",
	"Onanie macht taub. Hörst Du schlecht?",
	"Red Bull verleiht Flügel - aber wer will schon etwas von der AfD?",
	"Red Bull verleiht Flügel.",
	"Red Bull verleiht Flügel, aber du spielst bloß Maultrommel.",
	"Well, well, well, my little Droogies...",
	"Boah, ey!",
	"Bosetti will reden.",
	"Somnambulie ist kein Staat in Afrika.",
	"Wir müssen unsere Männlichkeit wieder entdecken.",
	"Nazis töten."
 };
 
 /* ------ END schwurbel.h ----------------------- */