# Auto-generated by AmigaED - regenerated automatically whenever a
# file is added to or removed from the project "mb_getcputype", and
# immediately before every build. Hand-edit this freely: AmigaED detects
# changes made outside itself and leaves this file untouched from then on -
# delete it to let AmigaED generate and manage it again.
# Toolchain: SAS/C (sc)
#
# SAS/C only runs on a real Amiga (or emulator) - AmigaED never runs
# this Makefile itself. Copy the project over and build it by hand
# (e.g. via smake) once you want to cross-check the build with SAS/C.

SCOPTS = ERRORREXX ICON MATH=IEEE
TARGET = mb_getcputype
SRCS   = cputype.c

all: $(TARGET)

$(TARGET): $(SRCS)
	sc $(SCOPTS) $(SRCS) LINK TO $(TARGET)

clean:
	delete $(TARGET)
